<?php

    include_once('../default_function.php');
    $menuNumber = $_POST["menuNumber"];

?>

<div class = "menu_community_guide">
    <div class = "menu_community_guide_top">
        <div class = "menu_community_guide_top_banner img_wrap">
            <img src = "/IMG/community_guide.webp?v=3" onload = "imageLoad(event);" alt = "">
        </div>
        <div class = "menu_community_guide_top_title">
            ...
        </div>
        <div class = "menu_community_guide_top_description">
            ...
        </div>
        <div class = "menu_community_guide_top_notice">
            <div class = "menu_community_guide_top_notice_icon">
                <!-- Generated by IcoMoon.io -->
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.070c-1.884-1.821-3.053-4.37-3.053-7.193 0-5.523 4.477-10 10-10 2.823 0 5.372 1.169 7.19 3.050l0.003 0.003c1.737 1.796 2.807 4.247 2.807 6.947 0 5.523-4.477 10-10 10-2.7 0-5.151-1.070-6.95-2.81l0.003 0.003zM9 5v6h2v-6h-2zM9 13v2h2v-2h-2z"></path></svg>
            </div>
            <div class = "menu_community_guide_top_notice_text">
                ...
            </div>
        </div>
    </div>
    <div class = "menu_community_guide_line"></div>
    <div class = "menu_community_guide_items">
        <div class = "menu_community_guide_item">
            <div class = "menu_community_guide_item_left">
                <div class = "menu_creator_guide_item_left_box">
                    1
                </div>
            </div>
            <div class = "menu_community_guide_item_right">
                <div class = "menu_community_guide_item_right_title">
                    ...
                </div>
                <div class = "menu_community_guide_item_right_description">
                    ...
                </div>
            </div>
        </div>
        <div class = "menu_community_guide_item">
            <div class = "menu_community_guide_item_left">
                <div class = "menu_creator_guide_item_left_box">
                    2
                </div>
            </div>
            <div class = "menu_community_guide_item_right">
                <div class = "menu_community_guide_item_right_title">
                    ...
                </div>
                <div class = "menu_community_guide_item_right_description">
                    ...
                </div>
            </div>
        </div>
        <div class = "menu_community_guide_item">
            <div class = "menu_community_guide_item_left">
                <div class = "menu_creator_guide_item_left_box">
                    3
                </div>
            </div>
            <div class = "menu_community_guide_item_right">
                <div class = "menu_community_guide_item_right_title">
                    ...
                </div>
                <div class = "menu_community_guide_item_right_description">
                    ...
                </div>
            </div>
        </div>
        <div class = "menu_community_guide_item">
            <div class = "menu_community_guide_item_left">
                <div class = "menu_creator_guide_item_left_box">
                    4
                </div>
            </div>
            <div class = "menu_community_guide_item_right">
                <div class = "menu_community_guide_item_right_title">
                    ...
                </div>
                <div class = "menu_community_guide_item_right_description">
                    ...
                </div>
            </div>
        </div>
    </div>
    <div class = "menu_community_guide_line"></div>
    <div class = "menu_community_guide_bottom">
        <div class = "menu_community_guide_bottom_creator_guide">
            <div class = "menu_community_guide_bottom_creator_guide_icon">
                <!-- Generated by IcoMoon.io -->
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M7 13.33c-2.384-1.15-4-3.549-4-6.325 0-3.866 3.134-7 7-7s7 3.134 7 7c0 2.776-1.616 5.174-3.958 6.306l-0.042 0.018v2.67h-6v-2.67zM7 17h6v1.5c0 0.83-0.67 1.5-1.5 1.5h-3c-0.828 0-1.5-0.672-1.5-1.5v0-1.5zM9 11.9v2.1h2v-2.1c2.299-0.481 4-2.492 4-4.899 0-2.761-2.239-5-5-5s-5 2.239-5 5c0 2.407 1.701 4.417 3.967 4.893l0.033 0.006z"></path></svg>
            </div>
            <div class = "menu_community_guide_bottom_creator_guide_text">
                ...
            </div>
        </div>
        <div class = "menu_community_guide_bottom_description">
            ...
        </div>
    </div>
</div>