<?php

    include_once('../default_function.php');
    $menuNumber = $_POST["menuNumber"];

?>

<div class = "menu_creator_guide">
    <div class = "menu_creator_guide_top">
        <div class = "menu_creator_guide_top_banner img_wrap">
            <img src = "/IMG/creator_guide.webp?v=2" onload = "imageLoad(event);" alt = "">
        </div>
        <div class = "menu_creator_guide_top_title">
            ...
        </div>
        <div class = "menu_creator_guide_top_description">
            ...
        </div>
        <div class = "menu_creator_guide_top_notice">
            <div class = "menu_creator_guide_top_notice_icon">
                <!-- Generated by IcoMoon.io -->
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.070c-1.884-1.821-3.053-4.37-3.053-7.193 0-5.523 4.477-10 10-10 2.823 0 5.372 1.169 7.19 3.050l0.003 0.003c1.737 1.796 2.807 4.247 2.807 6.947 0 5.523-4.477 10-10 10-2.7 0-5.151-1.070-6.95-2.81l0.003 0.003zM9 5v6h2v-6h-2zM9 13v2h2v-2h-2z"></path></svg>
            </div>
            <div class = "menu_creator_guide_top_notice_text">
                ...
            </div>
        </div>
    </div>
    <div class = "menu_creator_guide_line"></div>
    <div class = "menu_creator_guide_items">
        <div class = "menu_creator_guide_item">
            <div class = "menu_creator_guide_item_left">
                <div class = "menu_creator_guide_item_left_box">
                    1
                </div>
            </div>
            <div class = "menu_creator_guide_item_right">
                <div class = "menu_creator_guide_item_right_title">
                    ...
                </div>
                <div class = "menu_creator_guide_item_right_description">
                    ...
                </div>
            </div>
        </div>
        <div class = "menu_creator_guide_item">
            <div class = "menu_creator_guide_item_left">
                <div class = "menu_creator_guide_item_left_box">
                    2
                </div>
            </div>
            <div class = "menu_creator_guide_item_right">
                <div class = "menu_creator_guide_item_right_title">
                    ...
                </div>
                <div class = "menu_creator_guide_item_right_description">
                    ...
                </div>
            </div>
        </div>
        <div class = "menu_creator_guide_item">
            <div class = "menu_creator_guide_item_left">
                <div class = "menu_creator_guide_item_left_box">
                    3
                </div>
            </div>
            <div class = "menu_creator_guide_item_right">
                <div class = "menu_creator_guide_item_right_title">
                    ...
                </div>
                <div class = "menu_creator_guide_item_right_description">
                    ...
                </div>
            </div>
        </div>
        <div class = "menu_creator_guide_item">
            <div class = "menu_creator_guide_item_left">
                <div class = "menu_creator_guide_item_left_box">
                    4
                </div>
            </div>
            <div class = "menu_creator_guide_item_right">
                <div class = "menu_creator_guide_item_right_title">
                    ...
                </div>
                <div class = "menu_creator_guide_item_right_description">
                    ...
                </div>
            </div>
        </div>
    </div>
    <div class = "menu_creator_guide_line"></div>
    <div class = "menu_creator_guide_bottom">
        <div class = "menu_creator_guide_bottom_description">
            ...
        </div>
    </div>
</div>