<?php

    $menuNumber = $_POST["menuNumber"];

    include_once('../default_function.php');
    $userInfo = getMyLoginInfo();

    $number = $_POST["data"];

    $stmt = $pdo->prepare("SELECT data FROM cloud where type = 2 and number = :number and user_number = :user_number");
    $stmt->execute(array(
        ':number' => $number,
        ':user_number' => $userInfo["number"],
    ));
    $editor_json = $stmt->fetch()[0];

?>

<div class = "image_format_editor_header">
    <div class = "image_format_editor_header_left">
        <div class = "cloud_header_left_back md-ripples" onclick = "history.back();" onmouseenter = "hoverInformation(this, getLanguage('back'));">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><g transform="translate(-12.086 -0.24)"><rect width="3" height="35" rx="1.5" transform="translate(36.399 0.479) rotate(45)"></rect><rect width="3" height="35" rx="1.5" transform="translate(38.521 47.879) rotate(135)"></rect></g><rect width="49" height="3" rx="1.5" transform="translate(1 23.5)"></rect></g></svg>
        </div>
    </div>
    <div class = "image_format_editor_header_right">
        <div>
            <div class = "image_format_editor_header_right_more md-ripples" onclick = "moreButtonImageFormatEditor(<?php echo $menuNumber; ?>, this);" onmouseenter = "hoverInformation(this, getLanguage('image_format_editor_header:information'));" tabindex = "0">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><g transform="translate(-1 -1.061)"><circle cx="3" cy="3" r="3" transform="translate(23 4)"></circle><path d="M3,0A2.971,2.971,0,0,1,6,2.942,2.971,2.971,0,0,1,3,5.884,2.971,2.971,0,0,1,0,2.942,2.971,2.971,0,0,1,3,0Z" transform="translate(23 23)"></path><path d="M3,0A3.031,3.031,0,0,1,6,3.061,3.031,3.031,0,0,1,3,6.121,3.031,3.031,0,0,1,0,3.061,3.031,3.031,0,0,1,3,0Z" transform="translate(23 42)"></path></g></g></svg>
            </div>
        </div>
        <div>
            <div class = "image_format_editor_header_right_popup md-ripples" onclick = "imageFormatEditorInfoButton(this, <?php echo $menuNumber; ?>);" onmouseenter = "hoverInformation(this, getLanguage('image_format_editor_header:information'));" tabindex = "0">
                <!-- Generated by IcoMoon.io -->
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.070c-1.884-1.821-3.053-4.37-3.053-7.193 0-5.523 4.477-10 10-10 2.823 0 5.372 1.169 7.19 3.050l0.003 0.003c1.737 1.796 2.807 4.247 2.807 6.947 0 5.523-4.477 10-10 10-2.7 0-5.151-1.070-6.95-2.81l0.003 0.003zM15.66 15.66c1.449-1.449 2.344-3.45 2.344-5.66 0-4.421-3.584-8.004-8.004-8.004-2.21 0-4.211 0.896-5.66 2.344v0c-1.449 1.449-2.344 3.45-2.344 5.66 0 4.421 3.584 8.004 8.004 8.004 2.21 0 4.211-0.896 5.66-2.344v0zM9 5h2v6h-2v-6zM9 13h2v2h-2v-2z"></path></svg>
            </div>
        </div>
        <div>
            <div class = "image_format_editor_header_right_popup md-ripples" onclick = "imageFormatEditorPopupOpen();" onmouseenter = "hoverInformation(this, getLanguage('image_format_editor_header:sidebar'));" tabindex = "0">
                <!-- Generated by IcoMoon.io -->
                <svg style = "transform: rotate(180deg);" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5 2c-0.828 0-1.58 0.337-2.121 0.879s-0.879 1.293-0.879 2.121v14c0 0.828 0.337 1.58 0.879 2.121s1.293 0.879 2.121 0.879h14c0.828 0 1.58-0.337 2.121-0.879s0.879-1.293 0.879-2.121v-14c0-0.828-0.337-1.58-0.879-2.121s-1.293-0.879-2.121-0.879zM10 20v-16h9c0.276 0 0.525 0.111 0.707 0.293s0.293 0.431 0.293 0.707v14c0 0.276-0.111 0.525-0.293 0.707s-0.431 0.293-0.707 0.293zM8 4v16h-3c-0.276 0-0.525-0.111-0.707-0.293s-0.293-0.431-0.293-0.707v-14c0-0.276 0.111-0.525 0.293-0.707s0.431-0.293 0.707-0.293z"></path></svg>
            </div>
        </div>
        <div>
            <div class = "image_format_editor_header_right_save md-ripples" onclick = "imageFormatEditorSave(<?php echo $menuNumber; ?>);" onmouseenter = "hoverInformation(this, getLanguage('save'));" tabindex = "0">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M-4.438,42.27v0L.4,28.587,21.847,7.145a2.12,2.12,0,0,1,1.506-.632,1.945,1.945,0,0,1,1.387.567l7.071,7.071a1.944,1.944,0,0,1,.567,1.433,2.125,2.125,0,0,1-.632,1.459L10.3,38.487-4.436,42.27ZM23.387,9.839h0L3.162,30.064-.327,38.621l9.154-2.892L29.052,15.5,23.387,9.839Z" transform="translate(5.102 6.536)"></path><path d="M28.7,19.1a1.987,1.987,0,0,1-1.414-.586l-7.071-7.071a2,2,0,0,1,0-2.828l6.368-6.368a2,2,0,0,1,2.829,0l7.071,7.071a2,2,0,0,1,0,2.828L30.116,18.51A1.987,1.987,0,0,1,28.7,19.1ZM27.995,5.067h0l-4.95,4.95,5.666,5.665,4.95-4.949L27.995,5.067Z" transform="translate(12.102 -0.464)"></path></g></svg>
            </div>
        </div>
        <div>
            <div class = "header_right_button_profile md-ripples" onclick = "popupMyProfile(this);" onmouseenter = "hoverInformation(this, getLanguage('header_hover:profile'));">
                <div class = "header_right_button_profile_img img_wrap">
                    <div class = "profile_element">
                        <div class = "profile_info"><?php echo json_encode($userInfo["profile"]); ?></div>
                        <div class = "profile_image"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- 이미지 업로드 -->
<input class = "image_format_image_input" type = "file" onchange = "imageFormatUpload(this, <?php echo $menuNumber; ?>);" accept = "image/png, image/jpeg, image/webp, image/gif" multiple style = "display: none;">

<input style = "display: none;" id = "image_format_editor_number_<?php echo $menuNumber; ?>" value = "<?php echo $number; ?>">

<div class = "image_format_editor_contents">
    <div class = "image_format_editor_contents_items">
        <!-- Item -->
    </div>
</div>

<!-- 이전 json -->
<div class = "editor_json" style = "display: none;">
    <?php echo $editor_json; ?>
</div>




