<?php

    include_once('../default_function.php');
    $userInfo = getMyLoginInfo();

    if ($userInfo["isLogin"] == false) {
        echo "not login";
        exit;
    }

    $menuNumber = $_POST["menuNumber"];

?>

<div class = "menu_library">
    <div class = "menu_library_top scroll">
        <div class = "menu_library_top_wrap">
            <div class = "menu_library_top_profile_image md-ripples" onclick = "openPopupContents('change_profile');" onmouseenter="hoverInformation(this, getLanguage('header_hover:profile_edit'));">
                <div class = "menu_library_top_profile_image_inside header_right_button_profile_img">
                    ...
                </div>
                <div class = "menu_library_top_profile_image_icon">
                    <!-- Generated by IcoMoon.io -->
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M24 19v-11c0-0.828-0.337-1.58-0.879-2.121s-1.293-0.879-2.121-0.879h-3.465l-1.703-2.555c-0.182-0.27-0.486-0.445-0.832-0.445h-6c-0.326 0.002-0.64 0.158-0.832 0.445l-1.703 2.555h-3.465c-0.828 0-1.58 0.337-2.121 0.879s-0.879 1.293-0.879 2.121v11c0 0.828 0.337 1.58 0.879 2.121s1.293 0.879 2.121 0.879h18c0.828 0 1.58-0.337 2.121-0.879s0.879-1.293 0.879-2.121zM22 19c0 0.276-0.111 0.525-0.293 0.707s-0.431 0.293-0.707 0.293h-18c-0.276 0-0.525-0.111-0.707-0.293s-0.293-0.431-0.293-0.707v-11c0-0.276 0.111-0.525 0.293-0.707s0.431-0.293 0.707-0.293h4c0.346 0 0.65-0.175 0.832-0.445l1.703-2.555h4.93l1.703 2.555c0.192 0.287 0.506 0.443 0.832 0.445h4c0.276 0 0.525 0.111 0.707 0.293s0.293 0.431 0.293 0.707zM17 13c0-1.38-0.561-2.632-1.464-3.536s-2.156-1.464-3.536-1.464-2.632 0.561-3.536 1.464-1.464 2.156-1.464 3.536 0.561 2.632 1.464 3.536 2.156 1.464 3.536 1.464 2.632-0.561 3.536-1.464 1.464-2.156 1.464-3.536zM15 13c0 0.829-0.335 1.577-0.879 2.121s-1.292 0.879-2.121 0.879-1.577-0.335-2.121-0.879-0.879-1.292-0.879-2.121 0.335-1.577 0.879-2.121 1.292-0.879 2.121-0.879 1.577 0.335 2.121 0.879 0.879 1.292 0.879 2.121z"></path></svg>
                </div>
            </div>
            <div class = "menu_library_top_nickname_wrap">
                <div class = "menu_library_top_nickname">
                    <div class = "menu_library_top_nickname_text">
                        <?php echo $userInfo["nickname"]; ?>
                    </div>
                    <div class = "menu_library_top_nickname_icon md-ripples" onclick = "showLibraryChangeNicknameInputBox(<?php echo $menuNumber; ?>);" onmouseenter = "hoverInformation(this, getLanguage('menu_library_user_nickname_change_button'));">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M-4.438,42.27v0L.4,28.587,21.847,7.145a2.12,2.12,0,0,1,1.506-.632,1.945,1.945,0,0,1,1.387.567l7.071,7.071a1.944,1.944,0,0,1,.567,1.433,2.125,2.125,0,0,1-.632,1.459L10.3,38.487-4.436,42.27ZM23.387,9.839h0L3.162,30.064-.327,38.621l9.154-2.892L29.052,15.5,23.387,9.839Z" transform="translate(5.102 6.536)"></path><path d="M28.7,19.1a1.987,1.987,0,0,1-1.414-.586l-7.071-7.071a2,2,0,0,1,0-2.828l6.368-6.368a2,2,0,0,1,2.829,0l7.071,7.071a2,2,0,0,1,0,2.828L30.116,18.51A1.987,1.987,0,0,1,28.7,19.1ZM27.995,5.067h0l-4.95,4.95,5.666,5.665,4.95-4.949L27.995,5.067Z" transform="translate(12.102 -0.464)"></path></g></svg>
                    </div>
                </div>
                <div class = "menu_library_top_nickname_input_box">
                    <div class = "menu_library_top_nickname_input">
                        <input type = "text" placeholder = "..." original_value = "" onfocus = "libraryChangeNicknameInputFocus(this);" onblur = "libraryChangeNicknameInputBlur(this);" onkeydown = "libraryChangeNicknameInputKeyDown(this);">
                        <div class="menu_library_top_nickname_input_line_wrap"></div>
                    </div>
                    <div class = "menu_library_top_nickname_bottom">
                        <div class = "menu_library_top_nickname_bottom_cancel md-ripples" onmouseenter = "hoverInformation(this, getLanguage('menu_library_user_nickname_input_cancel'));" onclick = "hideLibraryChangeNicknameInputBox(<?php echo $menuNumber; ?>);">
                            <!-- Generated by IcoMoon.io -->
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18"><path d="M9 1c-4.418 0-8 3.582-8 8s3.582 8 8 8 8-3.582 8-8-3.582-8-8-8zM3 9c0-1.294 0.416-2.491 1.116-3.472l8.356 8.356c-0.981 0.7-2.178 1.116-3.472 1.116-3.309 0-6-2.691-6-6zM13.884 12.472l-8.356-8.356c0.981-0.7 2.178-1.116 3.472-1.116 3.309 0 6 2.691 6 6 0 1.294-0.416 2.491-1.116 3.472z"></path></svg>
                        </div>
                        <div class = "menu_library_top_nickname_bottom_submit md-ripples" onmouseenter = "hoverInformation(this, getLanguage('menu_library_user_nickname_change_button'));" onclick = "libraryChangeNicknameButton(<?php echo $menuNumber; ?>);">
                            <!-- Generated by IcoMoon.io -->
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.3 3.7l4 4-12.3 12.3h-4v-4l12.3-12.3zM13.7 2.3l2.3-2.3 4 4-2.3 2.3-4-4z"></path></svg>
                        </div>
                    </div>
                </div>
            </div>
            <div class = "menu_library_top_email">
                <?php echo $userInfo["email"]; ?>
            </div>
            <div class = "menu_library_top_info">
                <div class = "menu_library_top_info_item" value = "<?php echo $userInfo["workspace"]["countWorks"]; ?>">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M23.709,37.886h0L0,24.772,23.71,12.207,49.543,24.772,23.71,37.886Zm.134-22.5L6.133,24.772l17.71,9.8,19.3-9.8Z" transform="translate(0.228 -11.772)"></path><g transform="translate(1.456)"><path d="M1.451-.035A1.6,1.6,0,0,1,3,1.543L3.434,25.3a1.466,1.466,0,0,1-1.488,1.521A1.6,1.6,0,0,1,.4,25.244L-.037,1.486A1.466,1.466,0,0,1,1.451-.035Z" transform="translate(-0.648 25.64) rotate(-60)"></path><path d="M2.639.067A1.466,1.466,0,0,1,4.127,1.588L3.689,25.347a1.6,1.6,0,0,1-1.545,1.578A1.466,1.466,0,0,1,.656,25.4L1.094,1.645A1.6,1.6,0,0,1,2.639.067Z" transform="translate(43.172 22.047) rotate(60)"></path></g><g transform="translate(1.456 11)"><path d="M1.451-.035A1.6,1.6,0,0,1,3,1.543L3.434,25.3a1.466,1.466,0,0,1-1.488,1.521A1.6,1.6,0,0,1,.4,25.244L-.037,1.486A1.466,1.466,0,0,1,1.451-.035Z" transform="translate(-0.648 25.64) rotate(-60)"></path><path d="M2.639.067A1.466,1.466,0,0,1,4.127,1.588L3.689,25.347a1.6,1.6,0,0,1-1.545,1.578A1.466,1.466,0,0,1,.656,25.4L1.094,1.645A1.6,1.6,0,0,1,2.639.067Z" transform="translate(43.172 22.047) rotate(60)"></path></g></g></svg>
                    <span>...</span>
                </div>
                <div class = "menu_library_top_info_line"></div>
                <div class = "menu_library_top_info_item" value = "<?php echo $userInfo["cloud"]["useSize"]; ?>">
                    <div>...</div>
                    <span>...</span>
                </div>
            </div>
        </div>
    </div>
    <div class = "menu_library_contents">
        <div class = "menu_library_contents_load_menu_items">
            <div class = "menu_library_contents_load_menu_item md-ripples" onclick = "loadMenu_history();">
                <div class = "menu_library_contents_load_menu_item_left">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25-20a24.846,24.846,0,0,1-9.731-1.965,24.915,24.915,0,0,1-7.947-5.358,24.915,24.915,0,0,1-5.358-7.947A24.837,24.837,0,0,1,0-45H3A21.852,21.852,0,0,0,9.451-29.451,21.852,21.852,0,0,0,25-23,22.025,22.025,0,0,0,47-45,22.025,22.025,0,0,0,25-67,21.939,21.939,0,0,0,5.407-55H2.08a24.925,24.925,0,0,1,5.242-7.678,24.915,24.915,0,0,1,7.947-5.358A24.831,24.831,0,0,1,25-70a24.831,24.831,0,0,1,9.731,1.965,24.915,24.915,0,0,1,7.947,5.358,24.92,24.92,0,0,1,5.358,7.946A24.839,24.839,0,0,1,50-45a24.837,24.837,0,0,1-1.965,9.731,24.915,24.915,0,0,1-5.358,7.947,24.915,24.915,0,0,1-7.947,5.358A24.846,24.846,0,0,1,25-20Zm9.99-16.451a1.494,1.494,0,0,1-.749-.2L23.877-42.636A1.5,1.5,0,0,1,23-44V-59a1.5,1.5,0,0,1,1.5-1.5A1.5,1.5,0,0,1,26-59v14.126l9.742,5.623a1.5,1.5,0,0,1,.549,2.049A1.506,1.506,0,0,1,34.99-36.451Z" transform="translate(0 70)"></path><g transform="translate(-2 4)"><rect width="3" height="12" rx="1.5" transform="translate(2.871 2.017)"></rect><rect width="3" height="12" rx="1.5" transform="matrix(0.259, 0.966, -0.966, 0.259, 14.462, 8.276)"></rect></g></g></svg>
                </div>
                <div class = "menu_library_contents_load_menu_item_right">
                    <div class = "menu_library_contents_load_menu_item_right_title">
                        ...
                    </div>
                    <div class = "menu_library_contents_load_menu_item_right_description">
                        ...
                    </div>
                </div>
            </div>
            <div class = "menu_library_contents_load_menu_line"></div>
            <div class = "menu_library_contents_load_menu_item md-ripples" onclick = "loadMenu_my_work_list();">
                <div class = "menu_library_contents_load_menu_item_left">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><rect width="37" height="3" rx="1.5" transform="translate(1 2)"></rect><rect width="37" height="3" rx="1.5" transform="translate(1 18)"></rect><rect width="20" height="3" rx="1.5" transform="translate(1 34)"></rect><g transform="translate(2.518 0.541)"><rect width="3" height="17" rx="1.5" transform="translate(23.151 35.438) rotate(-45)"></rect><rect width="3" height="23" rx="1.5" transform="translate(44.884 26.041) rotate(30)"></rect></g></g></svg>
                </div>
                <div class = "menu_library_contents_load_menu_item_right">
                    <div class = "menu_library_contents_load_menu_item_right_title">
                        ...
                    </div>
                    <div class = "menu_library_contents_load_menu_item_right_description">
                        ...
                    </div>
                </div>
            </div>
            <div class = "menu_library_contents_load_menu_line"></div>
            <div class = "menu_library_contents_load_menu_item md-ripples" onclick = "loadMenu_my_user_list();">
                <div class = "menu_library_contents_load_menu_item_left">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M11,22A11,11,0,0,1,3.222,3.222,11,11,0,1,1,18.778,18.778,10.928,10.928,0,0,1,11,22ZM11,3a8,8,0,1,0,8,8A8.009,8.009,0,0,0,11,3Z" transform="translate(14)"></path><path d="M29.719,61H19A19,19,0,0,1,0,42V24A19,19,0,0,1,19,5h8.569a18.6,18.6,0,0,0-2.918,3.5H18.719a16.018,16.018,0,0,0-16,16v18a16.018,16.018,0,0,0,16,16h11a16.018,16.018,0,0,0,16-16V36.169a18.429,18.429,0,0,0,3-1.233V42a19,19,0,0,1-19,19Z" transform="translate(1.281 20)"></path><g transform="translate(1.849 -0.459)"><rect width="3" height="17" rx="1.5" transform="translate(23.151 35.438) rotate(-45)"></rect><rect width="3" height="23" rx="1.5" transform="translate(44.884 26.041) rotate(30)"></rect></g></g></svg>
                </div>
                <div class = "menu_library_contents_load_menu_item_right">
                    <div class = "menu_library_contents_load_menu_item_right_title">
                        ...
                    </div>
                    <div class = "menu_library_contents_load_menu_item_right_description">
                        ...
                    </div>
                </div>
            </div>
            <div class = "menu_library_contents_load_menu_line"></div>
            <div class = "menu_library_contents_load_menu_item md-ripples" onclick = "loadMenu_user(<?php echo $userInfo["number"]; ?>);">
                <div class = "menu_library_contents_load_menu_item_left">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M11,22A11,11,0,0,1,3.222,3.222,11,11,0,1,1,18.778,18.778,10.928,10.928,0,0,1,11,22ZM11,3a8,8,0,1,0,8,8A8.009,8.009,0,0,0,11,3Z" transform="translate(14)"></path><path d="M29.719,56H19A19,19,0,0,1,0,37V19A19,19,0,0,1,19,0H29.719a19,19,0,0,1,19,19V37a19,19,0,0,1-19,19Zm-11-52.5a16.018,16.018,0,0,0-16,16v18a16.018,16.018,0,0,0,16,16h11a16.018,16.018,0,0,0,16-16v-18a16.018,16.018,0,0,0-16-16Z" transform="translate(1.281 25)"></path></g></svg>
                </div>
                <div class = "menu_library_contents_load_menu_item_right">
                    <div class = "menu_library_contents_load_menu_item_right_title">
                        ...
                    </div>
                    <div class = "menu_library_contents_load_menu_item_right_description">
                        ...
                    </div>
                </div>
            </div>
            <div class = "menu_library_contents_load_menu_line"></div>
            <div class = "menu_library_contents_load_menu_item md-ripples" onclick = "loadMenu_notifications_settings();">
                <div class = "menu_library_contents_load_menu_item_left">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M42.282,39.4h0l-.226,0H1.251C.557,39.4.2,39.3.065,39.075c-.221-.363.152-1.085.769-2.282,1.4-2.715,4.315-8.364,4.6-18.745a21.434,21.434,0,0,1,1.682-8.6,15.31,15.31,0,0,1,4.146-5.562A17.322,17.322,0,0,1,22.285,0a16.042,16.042,0,0,1,10.5,4.409,18.085,18.085,0,0,1,5.659,13.638c.141,10.246,2.863,15.713,4.326,18.65.617,1.238.989,1.986.755,2.364C43.375,39.3,43,39.4,42.282,39.4ZM22.187,3.026c-6.61,0-13.7,4.015-13.76,15.285a46.872,46.872,0,0,1-2.09,13.2,29.949,29.949,0,0,1-1.958,4.9L39.3,36.4s0,0-.006-.009a27.524,27.524,0,0,1-1.879-4.733,47.874,47.874,0,0,1-2-13.351C35.34,7.268,27.28,3.075,22.217,3.026Z" transform="translate(3.124 0.378)"></path><path d="M6.4,0a6.4,6.4,0,0,1,6.4,6.4H0A6.4,6.4,0,0,1,6.4,0Z" transform="translate(30.704 50) rotate(180)"></path></g></svg>
                </div>
                <div class = "menu_library_contents_load_menu_item_right">
                    <div class = "menu_library_contents_load_menu_item_right_title">
                        ...
                    </div>
                    <div class = "menu_library_contents_load_menu_item_right_description">
                        ...
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>