<?php

    $menuNumber = $_POST["menuNumber"];

    include_once('../default_function.php');
    $userInfo = getMyLoginInfo();

    $number = $_POST["data"];

    $stmt = $pdo->prepare("SELECT data FROM cloud where type = 1 and number = :number and user_number = :user_number");
    $stmt->execute(array(
        ':number' => $number,
        ':user_number' => $userInfo["number"],
    ));
    $editor_json = $stmt->fetch()[0];

?>

<div class = "novel_editor_header">
    <div class = "novel_editor_header_left">
        <div class = "cloud_header_left_back md-ripples" onclick = "history.back();" onmouseenter = "hoverInformation(this, getLanguage('back'));">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><g transform="translate(-12.086 -0.24)"><rect width="3" height="35" rx="1.5" transform="translate(36.399 0.479) rotate(45)"></rect><rect width="3" height="35" rx="1.5" transform="translate(38.521 47.879) rotate(135)"></rect></g><rect width="49" height="3" rx="1.5" transform="translate(1 23.5)"></rect></g></svg>
        </div>
    </div>
    <div class = "novel_editor_header_right">
        <div>
            <div class = "novel_editor_header_right_more md-ripples" onclick = "moreButtonNovelEditor(<?php echo $menuNumber; ?>, this);" onmouseenter = "hoverInformation(this, getLanguage('view_more'));" tabindex = "0">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><g transform="translate(-1 -1.061)"><circle cx="3" cy="3" r="3" transform="translate(23 4)"></circle><path d="M3,0A2.971,2.971,0,0,1,6,2.942,2.971,2.971,0,0,1,3,5.884,2.971,2.971,0,0,1,0,2.942,2.971,2.971,0,0,1,3,0Z" transform="translate(23 23)"></path><path d="M3,0A3.031,3.031,0,0,1,6,3.061,3.031,3.031,0,0,1,3,6.121,3.031,3.031,0,0,1,0,3.061,3.031,3.031,0,0,1,3,0Z" transform="translate(23 42)"></path></g></g></svg>
            </div>
        </div>
        <div>
            <div class = "novel_editor_header_right_save md-ripples" onclick = "novelEditorSave(<?php echo $menuNumber; ?>);" onmouseenter = "hoverInformation(this, getLanguage('save'));" tabindex = "0">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M-4.438,42.27v0L.4,28.587,21.847,7.145a2.12,2.12,0,0,1,1.506-.632,1.945,1.945,0,0,1,1.387.567l7.071,7.071a1.944,1.944,0,0,1,.567,1.433,2.125,2.125,0,0,1-.632,1.459L10.3,38.487-4.436,42.27ZM23.387,9.839h0L3.162,30.064-.327,38.621l9.154-2.892L29.052,15.5,23.387,9.839Z" transform="translate(5.102 6.536)"></path><path d="M28.7,19.1a1.987,1.987,0,0,1-1.414-.586l-7.071-7.071a2,2,0,0,1,0-2.828l6.368-6.368a2,2,0,0,1,2.829,0l7.071,7.071a2,2,0,0,1,0,2.828L30.116,18.51A1.987,1.987,0,0,1,28.7,19.1ZM27.995,5.067h0l-4.95,4.95,5.666,5.665,4.95-4.949L27.995,5.067Z" transform="translate(12.102 -0.464)"></path></g></svg>
            </div>
        </div>
        <div>
            <div class = "header_right_button_profile md-ripples" onclick = "popupMyProfile(this);" onmouseenter = "hoverInformation(this, getLanguage('header_hover:profile'));">
                <div class = "header_right_button_profile_img img_wrap">
                    <div class = "profile_element">
                        <div class = "profile_info"><?php echo json_encode($userInfo["profile"]); ?></div>
                        <div class = "profile_image"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class = "novel_editor_header_info">
    <div class = "novel_editor_header_info_box">
        <div class = "novel_editor_header_info_box_item">
            <!-- Generated by IcoMoon.io -->
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><path d="M10.063 26l1.8-6h8.274l1.8 6h3.551l-6-20h-6.976l-6 20h3.551zM14.863 10h2.274l1.8 6h-5.874l1.8-6z"></path></svg>
            <spen id = "novel_editor_header_info_box_item_<?php echo $menuNumber; ?>_text_count">
                0
            </spen>
        </div>
        <div class = "novel_editor_header_info_box_item">
            <!-- Generated by IcoMoon.io -->
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><path d="M15.5 11h-11c-0.275 0-0.5 0.225-0.5 0.5v1c0 0.276 0.225 0.5 0.5 0.5h11c0.276 0 0.5-0.224 0.5-0.5v-1c0-0.275-0.224-0.5-0.5-0.5zM15.5 7h-11c-0.275 0-0.5 0.225-0.5 0.5v1c0 0.276 0.225 0.5 0.5 0.5h11c0.276 0 0.5-0.224 0.5-0.5v-1c0-0.275-0.224-0.5-0.5-0.5zM10.5 15h-6c-0.275 0-0.5 0.225-0.5 0.5v1c0 0.276 0.225 0.5 0.5 0.5h6c0.276 0 0.5-0.224 0.5-0.5v-1c0-0.275-0.224-0.5-0.5-0.5zM15.5 3h-11c-0.275 0-0.5 0.225-0.5 0.5v1c0 0.276 0.225 0.5 0.5 0.5h11c0.276 0 0.5-0.224 0.5-0.5v-1c0-0.275-0.224-0.5-0.5-0.5z"></path></svg>
            <spen id = "novel_editor_header_info_box_item_<?php echo $menuNumber; ?>_line_count">
                0
            </spen>
        </div>
    </div>
</div>


<!-- 이미지 업로드 -->
<input type = "file" onchange = "requestNovelEditorImageUpload(<?php echo $menuNumber; ?>);" id = "novel_editor_image_upload_<?php echo $menuNumber; ?>" accept = "image/png, image/jpeg, image/webp, image/gif" style = "display: none;">
<!-- 더빙 파일 업로드 -->
<input type = "file" onchange = "requestNovelEditorDubbingUpload(<?php echo $menuNumber; ?>);" id = "novel_editor_dubbing_upload_<?php echo $menuNumber; ?>" accept = "audio/*" style = "display: none;">

<input style = "display: none;" id = "novel_editor_number_<?php echo $menuNumber; ?>" value = "<?php echo $number; ?>">

<div class = "novel_editor_contents">
    <div class = "novel_editor_contents_box" id = "novel_editor_contents_box_<?php echo $menuNumber; ?>">
        <div class = "novel_editor_title" placeholder = "<?php echo getLanguage('novel_editor_please_title'); ?>" contenteditable = "true" onpaste = "contenteditable_paste(event);" onkeydown = "titleKeydown(event);" ondragenter = "novelEditorItemDrag(this);" onfocus = "showCaretBar = true; caretBarFocusElement = this;" onblur = "showCaretBar = false; caretBarFocusElement = null; previousNovelEditorFocusElement[<?php echo $menuNumber; ?>] = this;">
            <!-- 제목 -->
        </div>
    </div>
    <div class = "novel_editor_add_item md-ripples" onclick = "addItemNovelEditor(<?php echo $menuNumber; ?>);">
        <!-- Generated by IcoMoon.io -->
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M17.016 11.016q1.641 0 2.813 1.172t1.172 2.813-1.172 2.813-2.813 1.172h-2.016v2.016l-3-3 3-3v2.016h2.25q0.797 0 1.406-0.609t0.609-1.406-0.609-1.406-1.406-0.609h-13.266v-1.969h13.031zM20.016 5.016v1.969h-16.031v-1.969h16.031zM3.984 18.984v-1.969h6v1.969h-6z"></path></svg>
        <?php echo getLanguage("novel_editor_add_sentence"); ?>
    </div>
</div>

<!-- 이전 json -->
<div class = "editor_json" style = "display: none;">
    <?php echo $editor_json; ?>
</div>




