<?php

    include_once('../default_function.php');
    $userInfo = getMyLoginInfo();

    $menuNumber = $_POST["menuNumber"];
    $paymentHistoryNumber = $_POST["data"];

    $paymentHistoryInfo = getPaymentHistoryInfo($paymentHistoryNumber)[0];

?>

<div class = "info" style = "display: none;">
    <?php echo json_encode($paymentHistoryInfo); ?>
</div>

<div class = "menu_payment_history">
    <div class = "menu_payment_history_box">
        <div class = "menu_payment_history_box_pg_image">
            <img src = "..." onload = "imageLoad(event);" alt = "">
        </div>
        <div class = "menu_payment_history_box_pg_name">
            ...
        </div>
        <div class = "menu_payment_history_box_items">
            <div class = "menu_payment_history_box_item">
                <div class = "menu_payment_history_box_item_title">
                    ...
                </div>
                <div class = "payment_history_element_right_item_value">
                    <div class = "payment_history_element_right_item_value_icon">
                        ...
                    </div>
                    <div class = "payment_history_element_right_item_value_right">
                        <div class = "payment_history_element_right_item_value_right_title">
                            ...
                        </div>
                        <div class = "payment_history_element_right_item_value_right_description">
                            ...
                        </div>
                    </div>
                </div>
            </div>
            <div class = "menu_payment_history_box_item">
                <div class = "menu_payment_history_box_item_title">
                    ...
                </div>
                <div class = "payment_history_element_right_status" value = "2">
                    <div class = "payment_history_element_right_status_0">
                        <div class = "payment_history_element_right_status_icon">
                            <!-- Generated by IcoMoon.io -->
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19.293 5.293l-10.293 10.293-4.293-4.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414l5 5c0.391 0.391 1.024 0.391 1.414 0l11-11c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0z"></path></svg>
                        </div>
                        <div class = "payment_history_element_right_status_right">
                            <div class = "payment_history_element_right_status_right_title">
                                ...
                            </div>
                            <div class = "payment_history_element_right_status_right_date">
                                ...
                            </div>
                        </div>
                    </div>
                    <div class = "payment_history_element_right_status_1">
                        <div class = "payment_history_element_right_status_icon">
                            <!-- Generated by IcoMoon.io -->
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19.164 19.547c-1.641-2.5-3.669-3.285-6.164-3.484v1.437c0 0.534-0.208 1.036-0.586 1.414-0.756 0.756-2.077 0.751-2.823 0.005l-6.293-6.207c-0.191-0.189-0.298-0.444-0.298-0.713s0.107-0.524 0.298-0.712l6.288-6.203c0.754-0.755 2.073-0.756 2.829 0.001 0.377 0.378 0.585 0.88 0.585 1.414v1.704c4.619 0.933 8 4.997 8 9.796v1c0 0.442-0.29 0.832-0.714 0.958-0.095 0.027-0.19 0.042-0.286 0.042-0.331 0-0.646-0.165-0.836-0.452zM12.023 14.011c2.207 0.056 4.638 0.394 6.758 2.121-0.768-3.216-3.477-5.702-6.893-6.080-0.504-0.056-0.888-0.052-0.888-0.052v-3.497l-5.576 5.496 5.576 5.5v-3.499c0 0 0.738 0.010 1.023 0.011z"></path></svg>
                        </div>
                        <div class = "payment_history_element_right_status_right">
                            <div class = "payment_history_element_right_status_right_title">
                                ...
                            </div>
                            <div class = "payment_history_element_right_status_right_date">
                                ...
                            </div>
                        </div>
                    </div>
                    <div class = "payment_history_element_right_status_2">
                            <div class = "payment_history_element_right_status_icon">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"/></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M2,0A1.828,1.828,0,0,1,4,1.583V11.87c0,.874-4,0-4,0V1.583A1.828,1.828,0,0,1,2,0Z" transform="translate(34.785 31.957) rotate(135)"/><path d="M-3095,50a24.844,24.844,0,0,1-9.731-1.965,24.917,24.917,0,0,1-7.947-5.358,24.922,24.922,0,0,1-5.358-7.947A24.845,24.845,0,0,1-3120,25a24.845,24.845,0,0,1,1.965-9.731,24.922,24.922,0,0,1,5.358-7.947,24.917,24.917,0,0,1,7.947-5.358A24.844,24.844,0,0,1-3095,0a24.844,24.844,0,0,1,9.731,1.965,24.917,24.917,0,0,1,7.947,5.358,24.922,24.922,0,0,1,5.358,7.947A24.84,24.84,0,0,1-3070,25a24.84,24.84,0,0,1-1.965,9.731,24.922,24.922,0,0,1-5.358,7.947,24.917,24.917,0,0,1-7.947,5.358A24.844,24.844,0,0,1-3095,50Zm0-46a21.024,21.024,0,0,0-21,21,21.023,21.023,0,0,0,21,21,21.024,21.024,0,0,0,21-21A21.024,21.024,0,0,0-3095,4Z" transform="translate(3120)"/><rect width="4" height="16" rx="2" transform="translate(23 11)"/></g></svg>
                        </div>
                        <div class = "payment_history_element_right_status_right">
                            <div class = "payment_history_element_right_status_right_title">
                                ...
                            </div>
                            <div class = "payment_history_element_right_status_right_date">
                                ...
                            </div>
                        </div>
                    </div>
                    <div class = "payment_history_element_right_status_3">
                        <div class = "payment_history_element_right_status_icon">
                            <!-- Generated by IcoMoon.io -->
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.293 6.707l5.293 5.293-5.293 5.293c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0l5.293-5.293 5.293 5.293c0.391 0.391 1.024 0.391 1.414 0s0.391-1.024 0-1.414l-5.293-5.293 5.293-5.293c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0l-5.293 5.293-5.293-5.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414z"></path></svg>
                        </div>
                        <div class = "payment_history_element_right_status_right">
                            <div class = "payment_history_element_right_status_right_title">
                                ...
                            </div>
                            <div class = "payment_history_element_right_status_right_date">
                                ...
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class = "menu_payment_history_box_item">
                <div class = "menu_payment_history_box_item_title">
                    ...
                </div>
                <div class = "payment_history_element_right_item_value">
                    <div class = "payment_history_element_right_item_value_icon">
                        ...
                    </div>
                    <div class = "payment_history_element_right_item_value_right">
                        <div class = "payment_history_element_right_item_value_right_title">
                            ...
                        </div>
                        <div class = "payment_history_element_right_item_value_right_description">
                            ...
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class = "menu_payment_history_box_line"></div>
        <div class = "menu_payment_history_box_bottom">
            <div class = "menu_payment_history_box_button md-ripples">
                <div class = "menu_payment_history_box_button_icon">
                    <!-- Generated by IcoMoon.io -->
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M9.199 13.599c0.992 1.327 2.43 2.126 3.948 2.345s3.123-0.142 4.45-1.134c0.239-0.179 0.465-0.375 0.655-0.568l2.995-2.995c1.163-1.204 1.722-2.751 1.696-4.285s-0.639-3.061-1.831-4.211c-1.172-1.132-2.688-1.692-4.199-1.683-1.492 0.008-2.984 0.571-4.137 1.683l-1.731 1.721c-0.392 0.389-0.394 1.023-0.004 1.414s1.023 0.394 1.414 0.004l1.709-1.699c0.77-0.742 1.763-1.117 2.76-1.123 1.009-0.006 2.016 0.367 2.798 1.122 0.795 0.768 1.203 1.783 1.221 2.808s-0.355 2.054-1.11 2.836l-3.005 3.005c-0.114 0.116-0.263 0.247-0.428 0.37-0.885 0.662-1.952 0.902-2.967 0.756s-1.971-0.678-2.632-1.563c-0.331-0.442-0.957-0.533-1.4-0.202s-0.533 0.957-0.202 1.4zM14.801 10.401c-0.992-1.327-2.43-2.126-3.948-2.345s-3.124 0.142-4.451 1.134c-0.239 0.179-0.464 0.375-0.655 0.568l-2.995 2.995c-1.163 1.204-1.722 2.751-1.696 4.285s0.639 3.061 1.831 4.211c1.172 1.132 2.688 1.692 4.199 1.683 1.492-0.008 2.984-0.571 4.137-1.683l1.723-1.723c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0l-1.696 1.698c-0.77 0.742-1.763 1.117-2.76 1.123-1.009 0.006-2.016-0.367-2.798-1.122-0.795-0.768-1.203-1.783-1.221-2.808s0.355-2.054 1.11-2.836l3.005-3.005c0.114-0.116 0.263-0.247 0.428-0.37 0.885-0.662 1.952-0.902 2.967-0.756s1.971 0.678 2.632 1.563c0.331 0.442 0.957 0.533 1.4 0.202s0.533-0.957 0.202-1.4z"></path></svg>
                </div>
                <div class = "menu_payment_history_box_button_text">
                    ...
                </div>
            </div>
            <div class = "menu_payment_history_box_button md-ripples">
                <div class = "menu_payment_history_box_button_icon">
                    <!-- Generated by IcoMoon.io -->
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19.164 19.547c-1.641-2.5-3.669-3.285-6.164-3.484v1.437c0 0.534-0.208 1.036-0.586 1.414-0.756 0.756-2.077 0.751-2.823 0.005l-6.293-6.207c-0.191-0.189-0.298-0.444-0.298-0.713s0.107-0.524 0.298-0.712l6.288-6.203c0.754-0.755 2.073-0.756 2.829 0.001 0.377 0.378 0.585 0.88 0.585 1.414v1.704c4.619 0.933 8 4.997 8 9.796v1c0 0.442-0.29 0.832-0.714 0.958-0.095 0.027-0.19 0.042-0.286 0.042-0.331 0-0.646-0.165-0.836-0.452zM12.023 14.011c2.207 0.056 4.638 0.394 6.758 2.121-0.768-3.216-3.477-5.702-6.893-6.080-0.504-0.056-0.888-0.052-0.888-0.052v-3.497l-5.576 5.496 5.576 5.5v-3.499c0 0 0.738 0.010 1.023 0.011z"></path></svg>
                </div>
                <div class = "menu_payment_history_box_button_text">
                    ...
                </div>
            </div>
        </div>
        <div class = "menu_payment_history_box_line"></div>
    </div>
</div>