<?php

    include_once('../default_function.php');
    $userInfo = getMyLoginInfo();

    $menuNumber = $_POST["menuNumber"];
    $reviewedQuestionsNumber = $_POST["data"];
    $reviewedQuestionsInfo = getReviewedQuestionsInfo($reviewedQuestionsNumber)[0];

    if ($userInfo["isLogin"] == false || ($reviewedQuestionsInfo["userNumber"] != $userInfo["number"] && $userInfo["admin"] == false)) {
        echo "no permission";
        exit;
    }

?>

<div class = "my_user_number" style = "display: none;">
    <?php echo $userInfo["number"]; ?>
</div>
<div class = "info" style = "display: none;">
    <?php echo json_encode($reviewedQuestionsInfo); ?>
</div>

<div class = "menu_reviewed_questions">
    <div class = "menu_reviewed_questions_item">
        <div class = "menu_reviewed_questions_item_left md-ripples">
            <!-- profile -->
        </div>
        <div class = "menu_reviewed_questions_item_right">
            <div class = "menu_reviewed_questions_item_right_top">
                <div class = "menu_reviewed_questions_item_right_top_nickname md-ripples">
                    <!-- nickname -->
                </div>
                <div class = "menu_reviewed_questions_item_right_top_date">
                    <!-- date -->
                </div>
            </div>
            <div class = "menu_reviewed_questions_item_right_type">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,50A25.007,25.007,0,0,1,15.269,1.965,25.007,25.007,0,0,1,34.731,48.036,24.843,24.843,0,0,1,25,50ZM25,3A22,22,0,1,0,47,25,22.025,22.025,0,0,0,25,3Z"></path><g transform="translate(-24 6)"><rect width="3" height="24" rx="1.5" transform="translate(48 11)"></rect><rect width="3" height="4" rx="1.5" transform="translate(48 3)"></rect></g></g></svg>
                <div class = "menu_reviewed_questions_item_right_type_text">
                    <!-- type -->
                </div>
            </div>
            <div class = "menu_reviewed_questions_item_right_content">
                <!-- content -->
            </div>
            <div class = "menu_reviewed_questions_item_right_screenshot_wrap">
                <!-- screenshot -->
            </div>
        </div>
    </div>
    <div class = "menu_reviewed_questions_line"></div>
    <div class = "menu_reviewed_questions_reply">
        <div class = "menu_reviewed_questions_reply_highlighted">
            <!-- Generated by IcoMoon.io -->
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M7.5 5.578l2.484 1.406-1.406-2.484 1.406-2.484-2.484 1.406-2.484-1.406 1.406 2.484-1.406 2.484zM19.5 15.422l-2.484-1.406 1.406 2.484-1.406 2.484 2.484-1.406 2.484 1.406-1.406-2.484 1.406-2.484zM21.984 2.016l-2.484 1.406-2.484-1.406 1.406 2.484-1.406 2.484 2.484-1.406 2.484 1.406-1.406-2.484zM14.391 7.313q-0.328-0.328-0.727-0.328t-0.727 0.328l-11.625 11.625q-0.328 0.328-0.328 0.727t0.328 0.727l2.297 2.297q0.328 0.328 0.727 0.328t0.727-0.328l11.625-11.625q0.328-0.328 0.328-0.727t-0.328-0.68l-2.297-2.344zM13.359 12.797l-2.156-2.156 2.438-2.438 2.156 2.156-2.438 2.438z"></path></svg>
            <div class="menu_reviewed_questions_reply_highlighted_text">
                문의 답변
            </div>
        </div>
        <div class = "menu_reviewed_questions_reply_item">
            <div class = "menu_reviewed_questions_reply_item_left md-ripples">
                <!-- profile -->
            </div>
            <div class = "menu_reviewed_questions_reply_item_right">
                <div class = "menu_reviewed_questions_reply_item_right_top">
                    <div class = "menu_reviewed_questions_reply_item_right_top_nickname md-ripples">
                        <!-- nickname -->
                    </div>
                    <div class = "menu_reviewed_questions_reply_item_right_top_date">
                        <!-- date -->
                    </div>
                </div>
                <div class = "menu_reviewed_questions_reply_item_right_content">
                    <!-- content -->
                </div>
                <div class = "menu_reviewed_questions_reply_survey">
                    <div class = "menu_reviewed_questions_reply_survey_text">
                        ...
                    </div>
                    <div class = "menu_reviewed_questions_reply_survey_items">
                        <div class = "menu_reviewed_questions_reply_survey_item md-ripples" onclick = "likesButtonReviewedQuestionsReply(this, <?php echo $reviewedQuestionsInfo["number"] ?>);">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M11,25H2a2,2,0,0,1-2-2V2A2,2,0,0,1,2,0h9a2,2,0,0,1,2,2V23A2,2,0,0,1,11,25ZM3,3V22h7V3Z" transform="translate(0 22)"></path><path d="M29.891,44.45H1.733a1.868,1.868,0,0,1-1.224-.511A1.982,1.982,0,0,1,0,42.469c.016-1.947,0-21.23,0-22.05L14.682,2.173A7.441,7.441,0,0,1,19.5,0a5.453,5.453,0,0,1,2.441.588,4.405,4.405,0,0,1,2.637,3.769,5.912,5.912,0,0,1-.314,2.3c-.053.119-5.339,11.957-5.81,13.943H32.295a2.518,2.518,0,0,1,1.149.888,6.6,6.6,0,0,1,1.07,4.314A50.508,50.508,0,0,1,32.532,36.58l-2.641,7.869ZM19.7,2.931a4.877,4.877,0,0,0-2.353.816c-.917.543-14.2,17.567-14.332,17.739V41.439h24.8c2.66-7.819,3.451-12.257,3.647-14.6.212-2.54-.21-3.242-.215-3.249H14.125c.851-3,3.968-10.2,5.831-14.5.534-1.234.955-2.205,1.172-2.732.94-2.283.323-2.792-.652-3.262A1.764,1.764,0,0,0,19.7,2.931Z" transform="translate(14.814 2.158)"></path></g></svg>
                            <span>...</span>
                        </div>
                        <div class = "menu_reviewed_questions_reply_survey_item md-ripples" onclick = "dislikeButtonReviewedQuestionsReply(this, <?php echo $reviewedQuestionsInfo["number"] ?>);">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M11,25H2a2,2,0,0,1-2-2V2A2,2,0,0,1,2,0h9a2,2,0,0,1,2,2V23A2,2,0,0,1,11,25ZM3,3V22h7V3Z" transform="translate(49.33 27.158) rotate(180)"></path><path d="M29.891,44.45H1.733a1.868,1.868,0,0,1-1.224-.511A1.982,1.982,0,0,1,0,42.469c.016-1.947,0-21.23,0-22.05L14.682,2.173A7.441,7.441,0,0,1,19.5,0a5.453,5.453,0,0,1,2.441.588,4.405,4.405,0,0,1,2.637,3.769,5.912,5.912,0,0,1-.314,2.3c-.053.119-5.339,11.957-5.81,13.943H32.295a2.518,2.518,0,0,1,1.149.888,6.6,6.6,0,0,1,1.07,4.314A50.508,50.508,0,0,1,32.532,36.58l-2.641,7.869ZM19.7,2.931a4.877,4.877,0,0,0-2.353.816c-.917.543-14.2,17.567-14.332,17.739V41.439h24.8c2.66-7.819,3.451-12.257,3.647-14.6.212-2.54-.21-3.242-.215-3.249H14.125c.851-3,3.968-10.2,5.831-14.5.534-1.234.955-2.205,1.172-2.732.94-2.283.323-2.792-.652-3.262A1.764,1.764,0,0,0,19.7,2.931Z" transform="translate(34.517 47) rotate(180)"></path></g></svg>
                            <span>...</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>