<?php

    include_once('../default_function.php');
    $userInfo = getMyLoginInfo();

    $menuNumber = $_POST["menuNumber"];
    $data = json_decode($_POST["data"], true);
    $partNumber = $data["number"];
    $partInfo = getWorkPartInfo($partNumber, null, true)[0];
    $workInfo = getWorkInfo($partInfo["work_number"])[0];

    //챕터 제목 구하기
    $chapterTitle = getWorkChapterTitle($workInfo["number"], $partInfo["chapter"])[0];

    //댓글 정보
    $commentsUid = "part_" . $partInfo["number"];
    $commentsSort = 0; //인기 댓글 순
    $commentsNumbers = getCommentsNumbers($commentsUid, $commentsSort);
    $numbers = explode(",", $commentsNumbers);

    $commentsInfoMaxCount = (count($numbers) >= 20) ? 20 : count($numbers);
    $commentsInfo = getCommentsInfo(implode(",", array_slice($numbers, 0, $commentsInfoMaxCount)));

    //회차 리스트 정보
    $stmt = $pdo->prepare("SELECT number FROM work_part WHERE work_number = :work_number AND (public_status = 0 OR number = :number)");
    $stmt->execute(array(
        ':work_number' => $workInfo["number"],
        ':number' => $partNumber
    ));
    $partList = $stmt->fetchAll();
    $partListNumbers = array();
    $partListCount = count($partList);

    $currentPartNumberIndex = null;
    for ($i = 0; $i < $partListCount; $i++) {
        if ($partInfo["number"] == $partList[$i]["number"]) {
            $currentPartNumberIndex = $i;
        }
        $partListNumbers[$i] = $partList[$i]["number"];
    }

    $maxCount = 20;
    $removeIndex = $maxCount;
    if (($currentPartNumberIndex + $maxCount) > ($partListCount - 1)) {
        $removeIndex += ($currentPartNumberIndex + $maxCount) - ($partListCount - 1);
    }
    $minIndex = $currentPartNumberIndex - $removeIndex;
    if ($minIndex < 0) {
        $minIndex = 0;
    }

    $partListInfoMaxCount = (count($partListNumbers) >= 25) ? 25 : count($partListNumbers);
    $partListInfo = getWorkPartInfo(implode(",", array_slice($partListNumbers, $minIndex, 41)));

    //조회수 집계
    includeViewedPart($partInfo["number"]);

?>

<div class = "menu_title" style = "display: none;">
    <?php echo $partInfo["title"]; ?>
</div>
<div class = "comments_info" style = "display: none;">
    <?php
        echo json_encode(array(
            "numbers" => $commentsNumbers,
            "info" => $commentsInfo,
        ));
    ?>
</div>
<div class = "chapter_title" style = "display: none;">
    <?php echo $chapterTitle; ?>
</div>
<div class = "part_list_count" style = "display: none;">
    <?php echo json_encode($partListCount); ?>
</div>
<div class = "part_list_info" style = "display: none;">
    <?php echo json_encode($partListInfo); ?>
</div>
<div class = "part_info" style = "display: none;">
    <?php echo json_encode($partInfo); ?>
</div>
<div class = "work_info" style = "display: none;">
    <?php
        echo json_encode(array(
            "title" => $workInfo["title"],
            "description" => $workInfo["description"],
            "cover_image" => $workInfo["cover_image"],
            "ratings" => $workInfo["ratings"],
            "part" => $workInfo["part"],
            "views" => $workInfo["views"],
            "originator" => $workInfo["originator"]
        ));
    ?>
</div>

<div class = "menu_video">
    <div class = "menu_video_left">
        <div class = "menu_video_left_box">
            <div class = "video_player_dynamic_lighting">
                <div class = "video_player_dynamic_lighting_filter">
                    <canvas></canvas>
                </div>
            </div>
            <div class = "menu_video_left_box_in" menu_number = "<?php echo $menuNumber; ?>">
                <!-- video -->
            </div>
        </div>
        <div class = "menu_video_left_info">
            <div class = "menu_video_left_info_top">
                <div class = "menu_video_left_info_part_title">
                    ...
                </div>
                <div class = "menu_video_left_info_work_info">
                    <div class = "menu_video_left_info_work_info_left md-ripples" onclick = "loadMenu_work(<?php echo $workInfo["number"]; ?>);">
                        <img src = "<?php echo $workInfo["cover_image"] ?>" onload = "imageLoad(event);" alt = "">
                        <span>...</span>
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                    <div class = "menu_video_left_info_work_info_right">
                        <div class = "menu_video_left_info_work_info_right_button md-ripples" onclick = "menuVideoShare(<?php echo $menuNumber; ?>);">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><rect width="3" height="22" transform="translate(32.74 10.201) rotate(60)"></rect><rect width="3" height="22" transform="translate(34.437 37.201) rotate(120)"></rect><path d="M8,16a8,8,0,1,1,8-8A8.009,8.009,0,0,1,8,16ZM8,3a5,5,0,1,0,5,5A5.006,5.006,0,0,0,8,3Z" transform="translate(32)"></path><path d="M8,16a8,8,0,1,1,8-8A8.009,8.009,0,0,1,8,16ZM8,3a5,5,0,1,0,5,5A5.006,5.006,0,0,0,8,3Z" transform="translate(1 17)"></path><path d="M8,16a8,8,0,1,1,8-8A8.009,8.009,0,0,1,8,16ZM8,3a5,5,0,1,0,5,5A5.006,5.006,0,0,0,8,3Z" transform="translate(32 33)"></path></g></svg>
                        </div>
                        <div class = "menu_video_left_info_work_info_right_button md-ripples" onclick = "menuWorkMoreButton(this, <?php echo $menuNumber; ?>, <?php echo $workInfo["originator"]["number"]; ?>, <?php echo $workInfo["number"]; ?>);">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><g transform="translate(-1 -1.061)"><circle cx="3" cy="3" r="3" transform="translate(23 4)"></circle><path d="M3,0A2.971,2.971,0,0,1,6,2.942,2.971,2.971,0,0,1,3,5.884,2.971,2.971,0,0,1,0,2.942,2.971,2.971,0,0,1,3,0Z" transform="translate(23 23)"></path><path d="M3,0A3.031,3.031,0,0,1,6,3.061,3.031,3.031,0,0,1,3,6.121,3.031,3.031,0,0,1,0,3.061,3.031,3.031,0,0,1,3,0Z" transform="translate(23 42)"></path></g></g></svg>
                        </div>
                    </div>
                </div>
            </div>
            <div class = "menu_video_left_info_part_info_wrap">
                <div class = "menu_video_left_info_part_info_originator_wrap">
                    <div class = "menu_video_left_info_part_info_originator md-ripples" onclick = "loadMenu_user(<?php echo $workInfo["originator"]["number"]; ?>);">
                        <div class = "menu_video_left_info_part_info_originator_profile">
                            <!-- profile -->
                        </div>
                        <div class = "menu_video_left_info_part_info_originator_nickname">
                            ...
                        </div>
                    </div>
                </div>
                <div class = "menu_video_left_info_part_info_description">...</div>
                <div class = "menu_video_left_info_part_info_line"></div>
                <div class = "menu_video_left_info_part_info">
                    <div class = "menu_video_left_info_part_info_item">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,50A25.007,25.007,0,0,1,15.269,1.965,25.007,25.007,0,0,1,34.731,48.036,24.843,24.843,0,0,1,25,50ZM25,3A22,22,0,1,0,47,25,22.025,22.025,0,0,0,25,3Z"></path><g transform="translate(0 1)"><rect width="3" height="21" rx="1.5" transform="translate(23 6)"></rect><rect width="3" height="21" rx="1.5" transform="translate(44 24) rotate(90)"></rect></g></g></svg>
                        <span>...</span>
                    </div>
                    <div class = "menu_video_left_info_part_info_item">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M40.707,46.427h0a3.976,3.976,0,0,1-2.333-1.044c-3.13-2.487-11.917-9.316-12-9.383H5a5.006,5.006,0,0,1-5-5V5A5.006,5.006,0,0,1,5,0H45a5.006,5.006,0,0,1,5,5V31a5.005,5.005,0,0,1-5,5H42.466v9.106A2,2,0,0,1,40.707,46.427ZM4.906,3A1.985,1.985,0,0,0,3.016,4.9L2.984,31.027c0,.019.129,1.891,1.859,1.953H27.391l12.078,9.453V32.98h5.688A2.03,2.03,0,0,0,47,31l-.015-26.25c0-.017-.282-1.672-1.8-1.718Z" transform="translate(0 1.786)"></path></g></svg>
                        <span>...</span>
                    </div>
                    <div class = "menu_video_left_info_part_info_item">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,37a21.437,21.437,0,0,1-9.731-2.508,34.262,34.262,0,0,1-7.947-5.721A39.4,39.4,0,0,1,1.965,22.54,10.312,10.312,0,0,1,0,18.5a10.313,10.313,0,0,1,1.965-4.04A39.4,39.4,0,0,1,7.323,8.229a34.261,34.261,0,0,1,7.947-5.721A21.437,21.437,0,0,1,25,0a21.236,21.236,0,0,1,9.728,2.538A34.517,34.517,0,0,1,42.67,8.311a40.627,40.627,0,0,1,5.357,6.242A10.518,10.518,0,0,1,50,18.5c.01,1.175-2.446,5.3-6.467,9.358a35.762,35.762,0,0,1-8.228,6.3A21.562,21.562,0,0,1,25,37ZM25,2.964C13.381,2.964,3.264,16.237,3.264,18.5S13.381,34.036,25,34.036c7.276,0,13.532-5.214,16.613-8.322,3.016-3.042,5.109-6.244,5.1-7.214-.009-1.079-2.552-4.948-6.516-8.557C36.7,6.759,31.227,2.964,25,2.964Z" transform="translate(0 7)"></path><path d="M9.5,19A9.5,9.5,0,0,1,2.783,2.783,9.5,9.5,0,0,1,16.217,16.217,9.437,9.437,0,0,1,9.5,19Zm0-16.026A6.526,6.526,0,1,0,16.026,9.5,6.534,6.534,0,0,0,9.5,2.974Z" transform="translate(16 16)"></path></g></svg>
                        <span>...</span>
                    </div>
                </div>
            </div>
        </div>
        <div class = "menu_video_left_comments">
            <!-- comments -->
        </div>
    </div>
    <div class = "menu_video_right">
        <div class = "menu_video_right_part_list">
            <div class = "menu_video_right_part_list_top">
                <div class = "menu_video_right_part_list_top_left">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"/></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M1.5,0h47a1.5,1.5,0,0,1,0,3H1.5a1.5,1.5,0,0,1,0-3Z" transform="translate(0 10)"/><path d="M1.5,0h17a1.5,1.5,0,0,1,0,3H1.5a1.5,1.5,0,0,1,0-3Z" transform="translate(0 24)"/><path d="M1.5,0h17a1.5,1.5,0,0,1,0,3H1.5a1.5,1.5,0,0,1,0-3Z" transform="translate(0 37)"/><path d="M11.259,3.08a2,2,0,0,1,3.482,0l9.572,16.935A2,2,0,0,1,22.572,23H3.428a2,2,0,0,1-1.741-2.984Z" transform="translate(50 19) rotate(90)"/></g></svg>
                </div>
                <div class = "menu_video_right_part_list_top_right">
                    <div class = "menu_video_right_part_list_top_right_title">
                        ...
                    </div>
                    <div class = "menu_video_right_part_list_top_right_description">
                        ...
                    </div>
                </div>
            </div>
            <div class = "menu_video_right_part_list_items scroll">
                <!-- item -->
            </div>
        </div>
    </div>
</div>
<div class = "menu_video_part_list" onclick = "if (this.classList.contains('click_menu_video_part_list')) { this.classList.remove('click_menu_video_part_list'); } else { this.classList.remove('show_menu_video_part_list'); hideVideoPartListBoxItems(<?php echo $menuNumber; ?>); }">
    <div class = "menu_video_part_list_wrap">
        <div class = "menu_video_part_list_box_items_wrap" onclick = "this.parentElement.parentElement.classList.add('click_menu_video_part_list');">
            <div class = "menu_video_part_list_box_items_top">
                <div class = "menu_video_part_list_box_items_top_left">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"/></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M1.5,0h47a1.5,1.5,0,0,1,0,3H1.5a1.5,1.5,0,0,1,0-3Z" transform="translate(0 10)"/><path d="M1.5,0h17a1.5,1.5,0,0,1,0,3H1.5a1.5,1.5,0,0,1,0-3Z" transform="translate(0 24)"/><path d="M1.5,0h17a1.5,1.5,0,0,1,0,3H1.5a1.5,1.5,0,0,1,0-3Z" transform="translate(0 37)"/><path d="M11.259,3.08a2,2,0,0,1,3.482,0l9.572,16.935A2,2,0,0,1,22.572,23H3.428a2,2,0,0,1-1.741-2.984Z" transform="translate(50 19) rotate(90)"/></g></svg>
                </div>
                <div class = "menu_video_part_list_box_items_top_right">
                    <div class = "menu_video_part_list_box_items_top_right_title">
                        ...
                    </div>
                    <div class = "menu_video_part_list_box_items_top_right_description">
                        ...
                    </div>
                </div>
            </div>
            <div class = "menu_video_part_list_box_items scroll">
                <!-- item -->
            </div>
        </div>
        <div class = "menu_video_part_list_box_wrap" onclick = "this.parentElement.parentElement.classList.add('click_menu_video_part_list');">
            <div class = "menu_video_part_list_box md-ripples" onclick = "if (this.parentElement.parentElement.parentElement.classList.contains('show_menu_video_part_list')) { this.parentElement.parentElement.parentElement.classList.remove('show_menu_video_part_list'); hideVideoPartListBoxItems(<?php echo $menuNumber; ?>); } else { this.parentElement.parentElement.parentElement.classList.add('show_menu_video_part_list'); showVideoPartListBoxItems(<?php echo $menuNumber; ?>); }">
                <div class = "menu_video_part_list_box_left">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M22.406,4.461a3,3,0,0,1,5.187,0L47.379,38.492A3,3,0,0,1,44.786,43H5.214a3,3,0,0,1-2.594-4.508Z" transform="translate(50) rotate(90)"></path></g></svg>
                </div>
                <div class = "menu_video_part_list_box_thumbnail img_wrap">
                    <img src = "..." crossorigin = "anonymous" alt = "">
                </div>
                <div class = "menu_video_part_list_box_center">
                    <div class = "menu_video_part_list_box_center_title">
                        ...
                    </div>
                    <div class = "menu_video_part_list_box_center_description">
                        ...
                    </div>
                </div>
                <div class = "menu_video_part_list_box_right">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"/></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M887.214,176.5a1.5,1.5,0,0,1-1.061-.439L864.38,154.287l-21.773,21.773a1.5,1.5,0,1,1-2.121-2.121l22.834-22.834a1.5,1.5,0,0,1,2.121,0l22.834,22.834a1.5,1.5,0,0,1-1.061,2.561Z" transform="translate(-839.38 -138.583)"/></g></svg>
                </div>
            </div>
        </div>
    </div>
</div>