<?php

    include_once('../default_function.php');
    $userInfo = getMyLoginInfo();

    $menuNumber = $_POST["menuNumber"];
    $workListNumber = $_POST["data"];

    $workListInfo = getWorkListInfo($workListNumber, 0, null, true, true)[0];

    if ($workListInfo["status"] == 1) {
        echo 'no_permission';
        exit;
    } else if ($workListInfo["status"] == 2) {
        echo 'deleted';
        exit;
    }

    $numbers = explode(",", $workListInfo["work_numbers"]);
    $maxCount = (count($numbers) >= 24) ? 24 : count($numbers);
    $worksInfo = getWorkInfo(implode(",", array_slice($numbers, 0, $maxCount)));

    $info = array(
        'number' => $workListInfo["number"],
        'userNumber' => $workListInfo["user_number"],
        'profile' => $workListInfo["profile"],
        'nickname' => $workListInfo["nickname"],
        'title' => $workListInfo["title"],
        'publicStatus' => $workListInfo["public_status"],
        'count' => $workListInfo["count"],
        'updated_date' => $workListInfo["updated_date"],
        'workNumbers' => $workListInfo["work_numbers"],
        'worksInfo' => $worksInfo,
    );
    if (isset($workListInfo["thumbnail_image"])) {
        $info['thumbnailImage'] = $workListInfo["thumbnail_image"];
    }

?>

<div class = "menu_title" style = "display: none;">
    <?php echo $workListInfo["title"]; ?>
</div>
<div class = "work_list_info" style = "display: none;">
    <?php echo json_encode($info); ?>
</div>

<div class = "menu_work_list">
    <div class = "menu_work_list_left scroll">
        <div class = "menu_work_list_left_background">
            <img src = "..." onload = "imageLoad(event);" alt = "">
        </div>
        <div class = "menu_work_list_left_gradation"></div>
        <div class = "menu_work_list_left_wrap">
            <div class = "menu_work_list_left_thumbnail">
                <!-- html -->
            </div>
            <div class = "menu_work_list_left_title">
                <!-- html -->
            </div>
            <div class = "menu_work_list_left_title_wrap">
                <div class = "menu_work_list_left_change_title">
                    <!-- html -->
                </div>
                <div class = "menu_work_list_left_title_input_box">
                    <!-- html -->
                </div>
            </div>
            <div class = "menu_work_list_left_public_status" value = "0" popupwidth = "max-content">
                <div class = "menu_work_list_left_public_status_0">
                    <!-- Generated by IcoMoon.io -->
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5 12h14c0.276 0 0.525 0.111 0.707 0.293s0.293 0.431 0.293 0.707v7c0 0.276-0.111 0.525-0.293 0.707s-0.431 0.293-0.707 0.293h-14c-0.276 0-0.525-0.111-0.707-0.293s-0.293-0.431-0.293-0.707v-7c0-0.276 0.111-0.525 0.293-0.707s0.431-0.293 0.707-0.293zM8 10v-3c-0.001-1.106 0.445-2.105 1.169-2.831 0.723-0.724 1.719-1.172 2.821-1.174 1.030 0.003 1.948 0.378 2.652 1 0.638 0.565 1.097 1.332 1.28 2.209 0.113 0.541 0.642 0.888 1.183 0.775s0.888-0.642 0.775-1.183c-0.272-1.307-0.958-2.454-1.912-3.299-1.060-0.938-2.452-1.504-3.973-1.502-1.657 0.002-3.157 0.676-4.241 1.762s-1.756 2.587-1.754 4.243v3h-1c-0.828 0-1.58 0.337-2.121 0.879s-0.879 1.293-0.879 2.121v7c0 0.828 0.337 1.58 0.879 2.121s1.293 0.879 2.121 0.879h14c0.828 0 1.58-0.337 2.121-0.879s0.879-1.293 0.879-2.121v-7c0-0.828-0.337-1.58-0.879-2.121s-1.293-0.879-2.121-0.879z"></path></svg>
                    <span>...</span>
                    <div class = "menu_work_list_left_public_status_right_icon">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M17.418 6.109c0.272-0.268 0.709-0.268 0.979 0s0.271 0.701 0 0.969l-7.908 7.83c-0.27 0.268-0.707 0.268-0.979 0l-7.908-7.83c-0.27-0.268-0.27-0.701 0-0.969s0.709-0.268 0.979 0l7.419 7.141 7.418-7.141z"></path></svg>
                    </div>
                </div>
                <div class = "menu_work_list_left_public_status_1">
                    <!-- Generated by IcoMoon.io -->
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M15 8h3c1.105 0 2.103 0.447 2.828 1.172s1.172 1.723 1.172 2.828-0.447 2.103-1.172 2.828-1.723 1.172-2.828 1.172h-3c-0.552 0-1 0.448-1 1s0.448 1 1 1h3c1.657 0 3.158-0.673 4.243-1.757s1.757-2.586 1.757-4.243-0.673-3.158-1.757-4.243-2.586-1.757-4.243-1.757h-3c-0.552 0-1 0.448-1 1s0.448 1 1 1zM9 16h-3c-1.105 0-2.103-0.447-2.828-1.172s-1.172-1.723-1.172-2.828 0.447-2.103 1.172-2.828 1.723-1.172 2.828-1.172h3c0.552 0 1-0.448 1-1s-0.448-1-1-1h-3c-1.657 0-3.158 0.673-4.243 1.757s-1.757 2.586-1.757 4.243 0.673 3.158 1.757 4.243 2.586 1.757 4.243 1.757h3c0.552 0 1-0.448 1-1s-0.448-1-1-1zM8 13h8c0.552 0 1-0.448 1-1s-0.448-1-1-1h-8c-0.552 0-1 0.448-1 1s0.448 1 1 1z"></path></svg>
                    <span>...</span>
                    <div class = "menu_work_list_left_public_status_right_icon">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M17.418 6.109c0.272-0.268 0.709-0.268 0.979 0s0.271 0.701 0 0.969l-7.908 7.83c-0.27 0.268-0.707 0.268-0.979 0l-7.908-7.83c-0.27-0.268-0.27-0.701 0-0.969s0.709-0.268 0.979 0l7.419 7.141 7.418-7.141z"></path></svg>
                    </div>
                </div>
                <div class = "menu_work_list_left_public_status_2">
                    <!-- Generated by IcoMoon.io -->
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5 12h14c0.276 0 0.525 0.111 0.707 0.293s0.293 0.431 0.293 0.707v7c0 0.276-0.111 0.525-0.293 0.707s-0.431 0.293-0.707 0.293h-14c-0.276 0-0.525-0.111-0.707-0.293s-0.293-0.431-0.293-0.707v-7c0-0.276 0.111-0.525 0.293-0.707s0.431-0.293 0.707-0.293zM18 10v-3c0-1.657-0.673-3.158-1.757-4.243s-2.586-1.757-4.243-1.757-3.158 0.673-4.243 1.757-1.757 2.586-1.757 4.243v3h-1c-0.828 0-1.58 0.337-2.121 0.879s-0.879 1.293-0.879 2.121v7c0 0.828 0.337 1.58 0.879 2.121s1.293 0.879 2.121 0.879h14c0.828 0 1.58-0.337 2.121-0.879s0.879-1.293 0.879-2.121v-7c0-0.828-0.337-1.58-0.879-2.121s-1.293-0.879-2.121-0.879zM8 10v-3c0-1.105 0.447-2.103 1.172-2.828s1.723-1.172 2.828-1.172 2.103 0.447 2.828 1.172 1.172 1.723 1.172 2.828v3z"></path></svg>
                    <span>...</span>
                    <div class = "menu_work_list_left_public_status_right_icon">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M17.418 6.109c0.272-0.268 0.709-0.268 0.979 0s0.271 0.701 0 0.969l-7.908 7.83c-0.27 0.268-0.707 0.268-0.979 0l-7.908-7.83c-0.27-0.268-0.27-0.701 0-0.969s0.709-0.268 0.979 0l7.419 7.141 7.418-7.141z"></path></svg>
                    </div>
                </div>
            </div>
            <div class = "menu_work_list_left_updated_date">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,50A25.007,25.007,0,0,1,15.269,1.965,25.007,25.007,0,0,1,34.731,48.036,24.843,24.843,0,0,1,25,50ZM25,3A22,22,0,1,0,47,25,22.025,22.025,0,0,0,25,3Z"></path><g transform="translate(0 1)"><rect width="3" height="21" rx="1.5" transform="translate(23 6)"></rect><rect width="3" height="21" rx="1.5" transform="translate(44 24) rotate(90)"></rect></g></g></svg>
                <span>...</span>
            </div>
            <div class = "menu_work_list_left_button_items">
                <div class = "menu_work_list_left_button_item md-ripples" checked = "false" onclick = "workListSaveButton(<?php echo $menuNumber; ?>, <?php echo $workListNumber; ?>);" style = "display: none;" onmouseenter = "hoverInformation(this, getLanguage('work_list_save_button'));">
                    <div class = "menu_work_list_left_button_item_0">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"/></clipPath></defs><g id="a" clip-path="url(#b)"><rect width="37" height="3" rx="1.5" transform="translate(1 2)"/><rect width="37" height="3" rx="1.5" transform="translate(1 18)"/><rect width="20" height="3" rx="1.5" transform="translate(1 34)"/><g transform="translate(1 -1)"><g transform="translate(-0.075 1.515)"><rect width="3.678" height="23.098" rx="1.839" transform="translate(25.075 36.713) rotate(-90)"/></g><g transform="translate(71.018 -0.075) rotate(90)"><rect width="3.434" height="23.098" rx="1.717" transform="translate(25.075 36.469) rotate(-90)"/></g></g></g></svg>
                    </div>
                    <div class = "menu_work_list_left_button_item_1">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"/></clipPath></defs><g id="a" clip-path="url(#b)"><rect width="37" height="3" rx="1.5" transform="translate(1 2)"/><rect width="37" height="3" rx="1.5" transform="translate(1 18)"/><rect width="20" height="3" rx="1.5" transform="translate(1 34)"/><g transform="translate(2.518 0.541)"><rect width="3" height="17" rx="1.5" transform="translate(23.151 35.438) rotate(-45)"/><rect width="3" height="23" rx="1.5" transform="translate(44.884 26.041) rotate(30)"/></g></g></svg>
                    </div>
                </div>
                <div class = "menu_work_list_left_button_item md-ripples" checked = "false" onclick = "workListSortButton(<?php echo $menuNumber; ?>);" style = "display: none;" onmouseenter = "hoverInformation(this, getLanguage('work_list_sort_button'));">
                    <div class = "menu_work_list_left_button_item_0">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><rect width="50" height="3" rx="1.5" transform="translate(0 7)"></rect><rect width="16" height="3" rx="1.5" transform="translate(0 41)"></rect><rect width="33" height="3" rx="1.5" transform="translate(0 24)"></rect></g></svg>
                    </div>
                    <div class = "menu_work_list_left_button_item_1">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19.293 5.293l-10.293 10.293-4.293-4.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414l5 5c0.391 0.391 1.024 0.391 1.414 0l11-11c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0z"></path></svg>
                    </div>
                </div>
                <div class = "menu_work_list_left_button_item md-ripples" onclick = "workListMoreItems(this, <?php echo $menuNumber; ?>, <?php echo $workListNumber; ?>, <?php echo $workListInfo["user_number"]; ?>);" onmouseenter = "hoverInformation(this, getLanguage('view_more'));">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"/></clipPath></defs><g id="a" clip-path="url(#b)"><g transform="translate(51.061 -1) rotate(90)"><circle cx="3" cy="3" r="3" transform="translate(23 4)"/><path d="M3,0A2.971,2.971,0,0,1,6,2.942,2.971,2.971,0,0,1,3,5.884,2.971,2.971,0,0,1,0,2.942,2.971,2.971,0,0,1,3,0Z" transform="translate(23 23)"/><path d="M3,0A3.031,3.031,0,0,1,6,3.061,3.031,3.031,0,0,1,3,6.121,3.031,3.031,0,0,1,0,3.061,3.031,3.031,0,0,1,3,0Z" transform="translate(23 42)"/></g></g></svg>
                </div>
            </div>
            <div class = "menu_work_list_left_line"></div>
            <div class = "menu_work_list_left_user_info">
                <div class = "menu_work_list_left_user_info_profile">
                    ...
                </div>
                <div class = "menu_work_list_left_user_info_nickname md-ripples">
                    ...
                </div>
            </div>
        </div>
    </div>
    <div class = "menu_work_list_right">
        <div class = "menu_work_list_right_sort">
            <div class = "sort_box md-ripples" popupwidth = "max-content" value = "0" onchange = "workListOptionLoad(<?php echo $workListNumber; ?>, <?php echo $menuNumber; ?>);" onclick = "selectList(this, getWorkListSortItems());">
                <div class = "sort_box_title value_title"></div>
                <div class = "sort_box_icon">
                    <!-- Generated by IcoMoon.io -->
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M17.418 6.109c0.272-0.268 0.709-0.268 0.979 0s0.271 0.701 0 0.969l-7.908 7.83c-0.27 0.268-0.707 0.268-0.979 0l-7.908-7.83c-0.27-0.268-0.27-0.701 0-0.969s0.709-0.268 0.979 0l7.419 7.141 7.418-7.141z"></path></svg>
                </div>
            </div>
            <div class = "sort_box md-ripples" popupwidth = "max-content" value = "0" onchange = "workListOptionLoad(<?php echo $workListNumber; ?>, <?php echo $menuNumber; ?>);" onclick = "selectList(this, getWorkListWorkTypeItems());">
                <div class = "sort_box_title value_title"></div>
                <div class = "sort_box_icon">
                    <!-- Generated by IcoMoon.io -->
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M17.418 6.109c0.272-0.268 0.709-0.268 0.979 0s0.271 0.701 0 0.969l-7.908 7.83c-0.27 0.268-0.707 0.268-0.979 0l-7.908-7.83c-0.27-0.268-0.27-0.701 0-0.969s0.709-0.268 0.979 0l7.419 7.141 7.418-7.141z"></path></svg>
                </div>
            </div>
        </div>
        <div class = "work_resizing work_contents" order = "0" item_order = "0">
            <!-- item -->
        </div>
        <div class = "work_list_contents_loading" style = "padding: 20px; display: none;">
            <div class="showbox"><div class="loader" style="width: 35px;"><svg class="circular" viewBox="25 25 50 50"><circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="5" stroke-miterlimit="10"></circle></svg></div></div>
        </div>
        <div class = "menu_work_list_no_data" style = "display: none;">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"/></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M-3094.635,49.5H-3116.5a3,3,0,0,1-3-3V3.5a3,3,0,0,1,3-3h31a3,3,0,0,1,3,3V37.365L-3094.635,49.5Z" transform="translate(3126)" opacity="0.7"/><path d="M3151.333,49.5l12.293-12.293h-9.846a2.517,2.517,0,0,0-1.983.575,2.884,2.884,0,0,0-.464,2.039Z" transform="translate(-3120)" opacity="0.6"/></g></svg>
            <div class = "menu_work_list_no_data_title">
                ...
            </div>
            <div class = "menu_work_list_no_data_description">
                ...
            </div>
        </div>
    </div>
</div>