<?php

    $menuNumber = $_POST["menuNumber"];

    include_once('../../default_function.php');
    $userInfo = getMyLoginInfo();

    //폴더 개수
    $stmt = $pdo->prepare("SELECT COUNT(number) FROM cloud where type = 0 and user_number = :user_number");
    $stmt->execute(array(
        ':user_number' => $userInfo["number"],
    ));
    $countCloudFolder = $stmt->fetch()[0];

    //파일 개수
    $stmt = $pdo->prepare("SELECT COUNT(number) FROM cloud where type != 0 and user_number = :user_number");
    $stmt->execute(array(
        ':user_number' => $userInfo["number"],
    ));
    $countCloudFile = $stmt->fetch()[0];

    //프리미엄인지
    $isPremium = false;
    if ($userInfo["isLogin"] == true && $userInfo["rankInfo"]["rank"] == 5) {
        $isPremium = true;
    }

    //데이터 및 개인 정보 보호
    $whetherToSaveHistoryData = array(
        "isUseWorksHistory" => $userInfo["works_history_use"],
        "isUseSearchHistory" => $userInfo["search_history_use"],
        "isUseReplyNotifications" => $userInfo["reply_notifications_use"],
        "isUseActivityNotifications" => $userInfo["activity_notifications_use"],
        "isUseLouibooksNotifications" => $userInfo["louibooks_notifications_use"],
    );

    $stmt = $pdo->prepare("SELECT COUNT(random_key) FROM login_key WHERE user_number = :user_number");
    $stmt->execute(array(
        ':user_number' => $userInfo["number"]
    ));
    $loginKey = $stmt->fetch()[0];

    $isTwoFactorAuth = false;
    if ($userInfo["two_factor_auth_key"] != null) {
        $isTwoFactorAuth = true;
    }

    $stmt = $pdo->prepare("SELECT COUNT(random_key) FROM login_key WHERE user_number = :user_number AND security_issue = 1");
    $stmt->execute(array(
        ':user_number' => $userInfo["number"]
    ));
    $securityIssue = $stmt->fetch()[0];
    $isSecurityIssue = false;
    if ($securityIssue > 0) {
        $isSecurityIssue = true;
    }

?>

<div class = "user_info" style = "display: none">
    <?php
        echo json_encode(array(
            "nickname" => $userInfo["nickname"],
            "profile" => $userInfo["profile"],
            "gender" => $userInfo["gender"],
            "birthDate" => array(
                "year" => $userInfo["birth_year"],
                "month" => $userInfo["birth_month"],
                "day" => $userInfo["birth_day"]
            ),
            "whetherToSaveHistoryData" => $whetherToSaveHistoryData,
            "communityPermission" => $userInfo["community_permission"],
            "creatorPermission" => $userInfo["creator_permission"],
            "loginKey" => $loginKey,
            "rigorousAccessProcedures" => $userInfo["rigorous_access_procedures"],
            "isTwoFactorAuth" => $isTwoFactorAuth,
            "isSecurityIssue" => $isSecurityIssue,
            "isCreatorPermission" => $userInfo["creator_permission"],
            "isCommunityPermission" => $userInfo["community_permission"],
            "isPremium" => $isPremium
        ));
    ?>
</div>
<div class = "cloud_info" style = "display: none">
    <?php
        echo json_encode(array(
            "folderCount" => $countCloudFolder,
            "fileCount" => $countCloudFile,
            "useSize" => $userInfo["cloud"]["useSize"],
            "maxSize" => $userInfo["cloud"]["maxSize"]
        ));
    ?>
</div>

<div class = "menu_my_account_management">
    <div class = "menu_my_account_management_profile">
        <div class = "menu_my_account_management_profile_img md-ripples" onclick = "openPopupContents('change_profile');" onmouseenter = "hoverInformation(this, getLanguage('header_hover:profile_edit'));">
            <div class = "my_profile"></div>
            <div class = "menu_my_account_management_profile_img_icon">
                <!-- Generated by IcoMoon.io -->
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M24 19v-11c0-0.828-0.337-1.58-0.879-2.121s-1.293-0.879-2.121-0.879h-3.465l-1.703-2.555c-0.182-0.27-0.486-0.445-0.832-0.445h-6c-0.326 0.002-0.64 0.158-0.832 0.445l-1.703 2.555h-3.465c-0.828 0-1.58 0.337-2.121 0.879s-0.879 1.293-0.879 2.121v11c0 0.828 0.337 1.58 0.879 2.121s1.293 0.879 2.121 0.879h18c0.828 0 1.58-0.337 2.121-0.879s0.879-1.293 0.879-2.121zM22 19c0 0.276-0.111 0.525-0.293 0.707s-0.431 0.293-0.707 0.293h-18c-0.276 0-0.525-0.111-0.707-0.293s-0.293-0.431-0.293-0.707v-11c0-0.276 0.111-0.525 0.293-0.707s0.431-0.293 0.707-0.293h4c0.346 0 0.65-0.175 0.832-0.445l1.703-2.555h4.93l1.703 2.555c0.192 0.287 0.506 0.443 0.832 0.445h4c0.276 0 0.525 0.111 0.707 0.293s0.293 0.431 0.293 0.707zM17 13c0-1.38-0.561-2.632-1.464-3.536s-2.156-1.464-3.536-1.464-2.632 0.561-3.536 1.464-1.464 2.156-1.464 3.536 0.561 2.632 1.464 3.536 2.156 1.464 3.536 1.464 2.632-0.561 3.536-1.464 1.464-2.156 1.464-3.536zM15 13c0 0.829-0.335 1.577-0.879 2.121s-1.292 0.879-2.121 0.879-1.577-0.335-2.121-0.879-0.879-1.292-0.879-2.121 0.335-1.577 0.879-2.121 1.292-0.879 2.121-0.879 1.577 0.335 2.121 0.879 0.879 1.292 0.879 2.121z"></path></svg>
            </div>
        </div>
    </div>
    <div class = "menu_my_account_management_title">
        ...
    </div>
    <div class = "menu_my_account_management_description">
        ...
    </div>
    <div class = "menu_my_account_management_line"></div>
    <div class = "menu_my_account_management_notice" style = "display: none;">
        <div class = "menu_my_account_management_notice_items">
            <!-- item -->
        </div>
        <div class = "menu_my_account_management_line"></div>
    </div>
    <div class = "menu_my_account_management_items">
        <div class = "menu_my_account_management_item">
            <div class = "menu_my_account_management_item_top">
                <div class = "menu_my_account_management_item_title">
                    ...
                </div>
                <div class = "menu_my_account_management_item_description">
                    ...
                </div>
                <div class = "menu_my_account_management_item_cloud_items">
                    <div class = "menu_my_account_management_item_cloud">
                        <div class = "menu_my_account_management_item_cloud_left">
                            <?php
                                $strings = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
                                $unique = substr(str_shuffle($strings), 0, 10);
                                $svg = str_replace("{unique}", $unique, '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1000" height="1000" viewBox="0 0 1000 1000"> <defs> <style> .cls-1_{unique} { fill: #fff; } .cls-1_{unique}, .cls-2_{unique} { stroke: #707070; } .cls-11_{unique}, .cls-2_{unique} { fill: #1fdb64; } .cls-3_{unique} { clip-path: url(#clip-로고_18_{unique}); } .cls-4_{unique} { clip-path: url(#clip-path_{unique}); } .cls-5_{unique} { fill: #ff0045; } .cls-6_{unique} { clip-path: url(#clip-path-2_{unique}); } .cls-7_{unique} { fill: #fd0; } .cls-8_{unique} { clip-path: url(#clip-path-3_{unique}); } .cls-9_{unique} { fill: #08f; } .cls-10_{unique} { clip-path: url(#clip-path-4_{unique}); } </style> <clipPath id="clip-path_{unique}"> <rect id="사각형_5_{unique}" data-name="사각형 5_{unique}" class="cls-1_{unique}" width="298" height="1000" transform="matrix(0.966, 0.259, -0.259, 0.966, 142.635, -21.527)"/> </clipPath> <clipPath id="clip-path-2_{unique}"> <rect id="사각형_6_{unique}" data-name="사각형 6_{unique}" class="cls-1_{unique}" width="213" height="1000" transform="matrix(0.966, 0.259, -0.259, 0.966, 443.543, -10.55)"/> </clipPath> <clipPath id="clip-path-3_{unique}"> <rect id="사각형_7_{unique}" data-name="사각형 7_{unique}" class="cls-1_{unique}" width="248" height="1000" transform="matrix(0.966, 0.259, -0.259, 0.966, 646.21, 31.52)"/> </clipPath> <clipPath id="clip-path-4_{unique}"> <rect id="사각형_8_{unique}_{unique}" data-name="사각형 8_{unique}" class="cls-2_{unique}" width="450" height="673" transform="matrix(0.966, 0.259, -0.259, 0.966, 810.762, 370.231)"/> </clipPath> <clipPath id="clip-로고_18_{unique}"> <rect width="1000" height="1000"/> </clipPath> </defs> <g id="로고_18_{unique}" data-name="로고 – 18_{unique}" class="cls-3_{unique}"> <g id="그룹_32_{unique}" data-name="그룹 32_{unique}"> <g id="마스크_그룹_17_{unique}" data-name="마스크 그룹 17_{unique}" class="cls-4_{unique}"> <path id="패스_99_{unique}" data-name="패스 99_{unique}" class="cls-5_{unique}" d="M9713.928,5657.616h634.082s177.637,12.94,174.107-179.99-214.106-190.577-214.106-190.577,50.588-322.335-275.277-316.453S9755.1,5217.64,9755.1,5217.64s-234.1-25.881-232.928,215.282S9713.928,5657.616,9713.928,5657.616Z" transform="translate(-9522.169 -4814.185)"/> </g> <g id="마스크_그룹_18_{unique}" data-name="마스크 그룹 18_{unique}" class="cls-6_{unique}"> <path id="패스_98_{unique}" data-name="패스 98_{unique}" class="cls-7_{unique}" d="M9713.928,5657.616h634.082s177.637,12.94,174.107-179.99-214.106-190.577-214.106-190.577,50.588-322.335-275.277-316.453S9755.1,5217.64,9755.1,5217.64s-234.1-25.881-232.928,215.282S9713.928,5657.616,9713.928,5657.616Z" transform="translate(-9522.169 -4814.185)"/> </g> <g id="마스크_그룹_19_{unique}" data-name="마스크 그룹 19_{unique}" class="cls-8_{unique}" transform="translate(0.001)"> <path id="패스_100_{unique}" data-name="패스 100_{unique}" class="cls-9_{unique}" d="M9713.928,5657.616h634.082s177.637,12.94,174.107-179.99-214.106-190.577-214.106-190.577,50.588-322.335-275.277-316.453S9755.1,5217.64,9755.1,5217.64s-234.1-25.881-232.928,215.282S9713.928,5657.616,9713.928,5657.616Z" transform="translate(-9522.169 -4814.185)"/> </g> <g id="마스크_그룹_20_{unique}" data-name="마스크 그룹 20_{unique}" class="cls-10_{unique}"> <path id="패스_101_{unique}" data-name="패스 101_{unique}" class="cls-11_{unique}" d="M9713.928,5657.616h634.082s177.637,12.94,174.107-179.99-214.106-190.577-214.106-190.577,50.588-322.335-275.277-316.453S9755.1,5217.64,9755.1,5217.64s-234.1-25.881-232.928,215.282S9713.928,5657.616,9713.928,5657.616Z" transform="translate(-9522.169 -4814.185)"/> </g> </g> </g> </svg>');
                                echo $svg;
                            ?>
                        </div>
                        <div class = "menu_my_account_management_item_cloud_right">
                            <div class = "menu_my_account_management_item_cloud_right_title">
                                ...
                            </div>
                            <div class = "menu_my_account_management_item_cloud_right_lines">
                                <div class = "menu_my_account_management_item_cloud_right_line"></div>
                            </div>
                            <div class = "menu_my_account_management_item_cloud_right_bottom">
                                ...
                            </div>
                        </div>
                    </div>
                    <div class = "menu_my_account_management_item_cloud">
                        <div class = "menu_my_account_management_item_cloud_left">
                            <svg style = "width: 20px; height: 20px;" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,50A25.007,25.007,0,0,1,15.269,1.965,25.007,25.007,0,0,1,34.731,48.036,24.843,24.843,0,0,1,25,50ZM25,3A22,22,0,1,0,47,25,22.025,22.025,0,0,0,25,3Z"></path><g transform="translate(-24 6)"><rect width="3" height="24" rx="1.5" transform="translate(48 11)"></rect><rect width="3" height="4" rx="1.5" transform="translate(48 3)"></rect></g></g></svg>
                        </div>
                        <div class = "menu_my_account_management_item_cloud_right">
                            <div class = "menu_my_account_management_item_cloud_right_title">
                                ...
                            </div>
                            <div class = "menu_my_account_management_item_cloud_right_bottom">
                                ...
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class = "menu_my_account_management_item_bottom">
                <div class = "menu_my_account_management_item_line"></div>
                <div class = "menu_my_account_management_item_button md-ripples" onclick = "loadMenu_cloud();">
                    <div class = "menu_my_account_management_item_button_text">
                        ...
                    </div>
                    <div class = "menu_my_account_management_item_button_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
            </div>
        </div>
        <div class = "menu_my_account_management_item">
            <div class = "menu_my_account_management_item_top">
                <div class = "menu_my_account_management_item_title">
                    ...
                </div>
                <div class = "menu_my_account_management_item_description">
                    ...
                </div>
                <div class = "menu_my_account_management_item_check_items">
                    <div class = "menu_my_account_management_item_check_item">
                        <div class = "menu_my_account_management_item_check_item_icon">
                            <!-- Generated by IcoMoon.io -->
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 28"><path d="M16 17.672c0 1.359-0.891 2.328-2 2.328h-8c-1.109 0-2-0.969-2-2.328 0-2.422 0.594-5.109 3.062-5.109 0.766 0.438 1.797 1.188 2.938 1.188s2.172-0.75 2.938-1.188c2.469 0 3.062 2.688 3.062 5.109zM13.547 9.547c0 1.969-1.594 3.547-3.547 3.547s-3.547-1.578-3.547-3.547c0-1.953 1.594-3.547 3.547-3.547s3.547 1.594 3.547 3.547zM28 16.5v1c0 0.281-0.219 0.5-0.5 0.5h-9c-0.281 0-0.5-0.219-0.5-0.5v-1c0-0.281 0.219-0.5 0.5-0.5h9c0.281 0 0.5 0.219 0.5 0.5zM28 12.563v0.875c0 0.313-0.25 0.562-0.562 0.562h-8.875c-0.313 0-0.562-0.25-0.562-0.562v-0.875c0-0.313 0.25-0.562 0.562-0.562h8.875c0.313 0 0.562 0.25 0.562 0.562zM28 8.5v1c0 0.281-0.219 0.5-0.5 0.5h-9c-0.281 0-0.5-0.219-0.5-0.5v-1c0-0.281 0.219-0.5 0.5-0.5h9c0.281 0 0.5 0.219 0.5 0.5zM30 23.5v-19c0-0.266-0.234-0.5-0.5-0.5h-27c-0.266 0-0.5 0.234-0.5 0.5v19c0 0.266 0.234 0.5 0.5 0.5h5.5v-1.5c0-0.281 0.219-0.5 0.5-0.5h1c0.281 0 0.5 0.219 0.5 0.5v1.5h12v-1.5c0-0.281 0.219-0.5 0.5-0.5h1c0.281 0 0.5 0.219 0.5 0.5v1.5h5.5c0.266 0 0.5-0.234 0.5-0.5zM32 4.5v19c0 1.375-1.125 2.5-2.5 2.5h-27c-1.375 0-2.5-1.125-2.5-2.5v-19c0-1.375 1.125-2.5 2.5-2.5h27c1.375 0 2.5 1.125 2.5 2.5z"></path></svg>
                        </div>
                        <div class = "menu_my_account_management_item_check_item_right">
                            <div class = "menu_my_account_management_item_check_item_right_title">
                                ...
                            </div>
                            <div class = "menu_my_account_management_item_check_item_right_description">
                                ...
                            </div>
                        </div>
                    </div>
                    <div class = "menu_my_account_management_item_check_item">
                        <div class = "menu_my_account_management_item_check_item_icon">
                            <!-- Generated by IcoMoon.io -->
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M24 19v-11c0-0.828-0.337-1.58-0.879-2.121s-1.293-0.879-2.121-0.879h-3.465l-1.703-2.555c-0.182-0.27-0.486-0.445-0.832-0.445h-6c-0.326 0.002-0.64 0.158-0.832 0.445l-1.703 2.555h-3.465c-0.828 0-1.58 0.337-2.121 0.879s-0.879 1.293-0.879 2.121v11c0 0.828 0.337 1.58 0.879 2.121s1.293 0.879 2.121 0.879h18c0.828 0 1.58-0.337 2.121-0.879s0.879-1.293 0.879-2.121zM22 19c0 0.276-0.111 0.525-0.293 0.707s-0.431 0.293-0.707 0.293h-18c-0.276 0-0.525-0.111-0.707-0.293s-0.293-0.431-0.293-0.707v-11c0-0.276 0.111-0.525 0.293-0.707s0.431-0.293 0.707-0.293h4c0.346 0 0.65-0.175 0.832-0.445l1.703-2.555h4.93l1.703 2.555c0.192 0.287 0.506 0.443 0.832 0.445h4c0.276 0 0.525 0.111 0.707 0.293s0.293 0.431 0.293 0.707zM17 13c0-1.38-0.561-2.632-1.464-3.536s-2.156-1.464-3.536-1.464-2.632 0.561-3.536 1.464-1.464 2.156-1.464 3.536 0.561 2.632 1.464 3.536 2.156 1.464 3.536 1.464 2.632-0.561 3.536-1.464 1.464-2.156 1.464-3.536zM15 13c0 0.829-0.335 1.577-0.879 2.121s-1.292 0.879-2.121 0.879-1.577-0.335-2.121-0.879-0.879-1.292-0.879-2.121 0.335-1.577 0.879-2.121 1.292-0.879 2.121-0.879 1.577 0.335 2.121 0.879 0.879 1.292 0.879 2.121z"></path></svg>
                        </div>
                        <div class = "menu_my_account_management_item_check_item_right">
                            <div class = "menu_my_account_management_item_check_item_right_title">
                                ...
                            </div>
                            <div class = "menu_my_account_management_item_check_item_right_description" style = "display: flex;">
                                ...
                            </div>
                        </div>
                    </div>
                    <div class = "menu_my_account_management_item_check_item">
                        <div class = "menu_my_account_management_item_check_item_icon">
                            ...
                        </div>
                        <div class = "menu_my_account_management_item_check_item_right">
                            <div class = "menu_my_account_management_item_check_item_right_title">
                                ...
                            </div>
                            <div class = "menu_my_account_management_item_check_item_right_description">
                                ...
                            </div>
                        </div>
                    </div>
                    <div class = "menu_my_account_management_item_check_item">
                        <div class = "menu_my_account_management_item_check_item_icon">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,50A25.007,25.007,0,0,1,15.269,1.965,25.007,25.007,0,0,1,34.731,48.036,24.843,24.843,0,0,1,25,50ZM25,3A22,22,0,1,0,47,25,22.025,22.025,0,0,0,25,3Z"></path><g transform="translate(0 1)"><rect width="3" height="21" rx="1.5" transform="translate(23 6)"></rect><rect width="3" height="21" rx="1.5" transform="translate(44 24) rotate(90)"></rect></g></g></svg>
                        </div>
                        <div class = "menu_my_account_management_item_check_item_right">
                            <div class = "menu_my_account_management_item_check_item_right_title">
                                ...
                            </div>
                            <div class = "menu_my_account_management_item_check_item_right_description">
                                ...
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class = "menu_my_account_management_item_bottom">
                <div class = "menu_my_account_management_item_line"></div>
                <div class = "menu_my_account_management_item_button md-ripples" onclick = "loadMyAccount_personal_info();">
                    <div class = "menu_my_account_management_item_button_text">
                        ...
                    </div>
                    <div class = "menu_my_account_management_item_button_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
            </div>
        </div>
        <div class = "menu_my_account_management_item">
            <div class = "menu_my_account_management_item_top">
                <div class = "menu_my_account_management_item_title">
                    ...
                </div>
                <div class = "menu_my_account_management_item_description">
                    ...
                </div>
                <div class = "menu_my_account_management_item_check_items">
                    <div class = "menu_my_account_management_item_check_item">
                        <div class = "menu_my_account_management_item_check_item_icon">
                            <div class = "menu_my_account_management_item_check_item_icon_true">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19.293 5.293l-10.293 10.293-4.293-4.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414l5 5c0.391 0.391 1.024 0.391 1.414 0l11-11c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0z"></path></svg>
                            </div>
                            <div class = "menu_my_account_management_item_check_item_icon_false">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.293 6.707l5.293 5.293-5.293 5.293c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0l5.293-5.293 5.293 5.293c0.391 0.391 1.024 0.391 1.414 0s0.391-1.024 0-1.414l-5.293-5.293 5.293-5.293c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0l-5.293 5.293-5.293-5.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414z"></path></svg>
                            </div>
                        </div>
                        <div class = "menu_my_account_management_item_check_item_right">
                            <div class = "menu_my_account_management_item_check_item_right_title">
                                ...
                            </div>
                            <div class = "menu_my_account_management_item_check_item_right_description">
                                ...
                            </div>
                        </div>
                    </div>
                    <div class = "menu_my_account_management_item_check_item">
                        <div class = "menu_my_account_management_item_check_item_icon">
                            <div class = "menu_my_account_management_item_check_item_icon_true">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19.293 5.293l-10.293 10.293-4.293-4.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414l5 5c0.391 0.391 1.024 0.391 1.414 0l11-11c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0z"></path></svg>
                            </div>
                            <div class = "menu_my_account_management_item_check_item_icon_false">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.293 6.707l5.293 5.293-5.293 5.293c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0l5.293-5.293 5.293 5.293c0.391 0.391 1.024 0.391 1.414 0s0.391-1.024 0-1.414l-5.293-5.293 5.293-5.293c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0l-5.293 5.293-5.293-5.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414z"></path></svg>
                            </div>
                        </div>
                        <div class = "menu_my_account_management_item_check_item_right">
                            <div class = "menu_my_account_management_item_check_item_right_title">
                                ...
                            </div>
                            <div class = "menu_my_account_management_item_check_item_right_description">
                                ...
                            </div>
                        </div>
                    </div>
                    <div class = "menu_my_account_management_item_check_item">
                        <div class = "menu_my_account_management_item_check_item_icon">
                            <div class = "menu_my_account_management_item_check_item_icon_true">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19.293 5.293l-10.293 10.293-4.293-4.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414l5 5c0.391 0.391 1.024 0.391 1.414 0l11-11c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0z"></path></svg>
                            </div>
                            <div class = "menu_my_account_management_item_check_item_icon_false">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.293 6.707l5.293 5.293-5.293 5.293c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0l5.293-5.293 5.293 5.293c0.391 0.391 1.024 0.391 1.414 0s0.391-1.024 0-1.414l-5.293-5.293 5.293-5.293c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0l-5.293 5.293-5.293-5.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414z"></path></svg>
                            </div>
                        </div>
                        <div class = "menu_my_account_management_item_check_item_right">
                            <div class = "menu_my_account_management_item_check_item_right_title">
                                ...
                            </div>
                            <div class = "menu_my_account_management_item_check_item_right_description">
                                ...
                            </div>
                        </div>
                    </div>
                    <div class = "menu_my_account_management_item_check_item">
                        <div class = "menu_my_account_management_item_check_item_icon">
                            <div class = "menu_my_account_management_item_check_item_icon_true">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19.293 5.293l-10.293 10.293-4.293-4.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414l5 5c0.391 0.391 1.024 0.391 1.414 0l11-11c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0z"></path></svg>
                            </div>
                            <div class = "menu_my_account_management_item_check_item_icon_false">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.293 6.707l5.293 5.293-5.293 5.293c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0l5.293-5.293 5.293 5.293c0.391 0.391 1.024 0.391 1.414 0s0.391-1.024 0-1.414l-5.293-5.293 5.293-5.293c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0l-5.293 5.293-5.293-5.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414z"></path></svg>
                            </div>
                        </div>
                        <div class = "menu_my_account_management_item_check_item_right">
                            <div class = "menu_my_account_management_item_check_item_right_title">
                                ...
                            </div>
                            <div class = "menu_my_account_management_item_check_item_right_description">
                                ...
                            </div>
                        </div>
                    </div>
                    <div class = "menu_my_account_management_item_check_item">
                        <div class = "menu_my_account_management_item_check_item_icon">
                            <div class = "menu_my_account_management_item_check_item_icon_true">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19.293 5.293l-10.293 10.293-4.293-4.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414l5 5c0.391 0.391 1.024 0.391 1.414 0l11-11c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0z"></path></svg>
                            </div>
                            <div class = "menu_my_account_management_item_check_item_icon_false">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.293 6.707l5.293 5.293-5.293 5.293c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0l5.293-5.293 5.293 5.293c0.391 0.391 1.024 0.391 1.414 0s0.391-1.024 0-1.414l-5.293-5.293 5.293-5.293c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0l-5.293 5.293-5.293-5.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414z"></path></svg>
                            </div>
                        </div>
                        <div class = "menu_my_account_management_item_check_item_right">
                            <div class = "menu_my_account_management_item_check_item_right_title">
                                ...
                            </div>
                            <div class = "menu_my_account_management_item_check_item_right_description">
                                ...
                            </div>
                        </div>
                    </div>
                    <div class = "menu_my_account_management_item_check_item">
                        <div class = "menu_my_account_management_item_check_item_icon">
                            <div class = "menu_my_account_management_item_check_item_icon_true">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19.293 5.293l-10.293 10.293-4.293-4.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414l5 5c0.391 0.391 1.024 0.391 1.414 0l11-11c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0z"></path></svg>
                            </div>
                            <div class = "menu_my_account_management_item_check_item_icon_false">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.293 6.707l5.293 5.293-5.293 5.293c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0l5.293-5.293 5.293 5.293c0.391 0.391 1.024 0.391 1.414 0s0.391-1.024 0-1.414l-5.293-5.293 5.293-5.293c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0l-5.293 5.293-5.293-5.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414z"></path></svg>
                            </div>
                        </div>
                        <div class = "menu_my_account_management_item_check_item_right">
                            <div class = "menu_my_account_management_item_check_item_right_title">
                                ...
                            </div>
                            <div class = "menu_my_account_management_item_check_item_right_description">
                                ...
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class = "menu_my_account_management_item_bottom">
                <div class = "menu_my_account_management_item_line"></div>
                <div class = "menu_my_account_management_item_button md-ripples" onclick = "loadMyAccount_privacy();">
                    <div class = "menu_my_account_management_item_button_text">
                        ...
                    </div>
                    <div class = "menu_my_account_management_item_button_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
            </div>
        </div>
        <div class = "menu_my_account_management_item">
            <div class = "menu_my_account_management_item_top">
                <div class = "menu_my_account_management_item_title">
                    ...
                </div>
                <div class = "menu_my_account_management_item_description">
                    ...
                </div>
                <div class = "menu_my_account_management_item_check_items">
                    <div class = "menu_my_account_management_item_check_item">
                        <div class = "menu_my_account_management_item_check_item_icon" checked = "false">
                            <div class = "menu_my_account_management_item_check_item_icon_true">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19.293 5.293l-10.293 10.293-4.293-4.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414l5 5c0.391 0.391 1.024 0.391 1.414 0l11-11c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0z"></path></svg>
                            </div>
                            <div class = "menu_my_account_management_item_check_item_icon_false">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.293 6.707l5.293 5.293-5.293 5.293c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0l5.293-5.293 5.293 5.293c0.391 0.391 1.024 0.391 1.414 0s0.391-1.024 0-1.414l-5.293-5.293 5.293-5.293c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0l-5.293 5.293-5.293-5.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414z"></path></svg>
                            </div>
                        </div>
                        <div class = "menu_my_account_management_item_check_item_right">
                            <div class = "menu_my_account_management_item_check_item_right_title">
                                ...
                            </div>
                            <div class = "menu_my_account_management_item_check_item_right_description">
                                ...
                            </div>
                        </div>
                    </div>
                    <div class = "menu_my_account_management_item_check_item">
                        <div class = "menu_my_account_management_item_check_item_icon" checked = "false">
                            <div class = "menu_my_account_management_item_check_item_icon_true">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M19.293 5.293l-10.293 10.293-4.293-4.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414l5 5c0.391 0.391 1.024 0.391 1.414 0l11-11c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0z"></path></svg>
                            </div>
                            <div class = "menu_my_account_management_item_check_item_icon_false">
                                <!-- Generated by IcoMoon.io -->
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5.293 6.707l5.293 5.293-5.293 5.293c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0l5.293-5.293 5.293 5.293c0.391 0.391 1.024 0.391 1.414 0s0.391-1.024 0-1.414l-5.293-5.293 5.293-5.293c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0l-5.293 5.293-5.293-5.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414z"></path></svg>
                            </div>
                        </div>
                        <div class = "menu_my_account_management_item_check_item_right">
                            <div class = "menu_my_account_management_item_check_item_right_title">
                                ...
                            </div>
                            <div class = "menu_my_account_management_item_check_item_right_description">
                                ...
                            </div>
                        </div>
                    </div>
                    <div class = "menu_my_account_management_item_check_item">
                        <div class = "menu_my_account_management_item_check_item_icon">
                            <!-- Generated by IcoMoon.io -->
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M20.293 1.293l-2 2c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0l2-2c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0zM12.092 10.898c-1.262-1.244-2.908-1.869-4.553-1.873-1.652-0.003-3.308 0.62-4.578 1.873-1.277 1.26-1.923 2.921-1.935 4.583s0.614 3.332 1.874 4.609c1.34 1.323 3.009 1.946 4.671 1.935s3.323-0.657 4.583-1.935 1.884-2.947 1.873-4.609-0.657-3.323-1.935-4.583zM10.688 12.322c0.885 0.873 1.332 2.020 1.339 3.173s-0.424 2.306-1.297 3.191-2.020 1.332-3.173 1.339-2.306-0.424-3.191-1.297c-0.916-0.927-1.347-2.080-1.339-3.233s0.455-2.3 1.339-3.173c0.879-0.867 2.023-1.299 3.169-1.296 1.141 0.002 2.279 0.435 3.152 1.296zM12.097 12.317l4.11-4.11c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0l-4.11 4.11c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0zM14.793 8.207l3 3c0.391 0.391 1.024 0.391 1.414 0l3.5-3.5c0.391-0.391 0.391-1.024 0-1.414l-3-3c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414l2.293 2.293-2.086 2.086-2.293-2.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414zM16.207 8.207l3.5-3.5c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0l-3.5 3.5c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0z"></path></svg>
                        </div>
                        <div class = "menu_my_account_management_item_check_item_right">
                            <div class = "menu_my_account_management_item_check_item_right_title">
                                ...
                            </div>
                            <div class = "menu_my_account_management_item_check_item_right_description">
                                ...
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class = "menu_my_account_management_item_bottom">
                <div class = "menu_my_account_management_item_line"></div>
                <div class = "menu_my_account_management_item_button md-ripples" onclick = "loadMyAccount_security();">
                    <div class = "menu_my_account_management_item_button_text">
                        ...
                    </div>
                    <div class = "menu_my_account_management_item_button_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class = "menu_my_account_management_line"></div>
    <div class = "menu_my_account_management_bottom">
        ...
    </div>
</div>