<?php

    $menuNumber = $_POST["menuNumber"];

    include_once('../../default_function.php');
    $userInfo = getMyLoginInfo();

    //로그인 키 갯수
    $stmt = $pdo->prepare("SELECT COUNT(random_key) FROM login_key WHERE user_number = :user_number");
    $stmt->execute(array(
        ':user_number' => $userInfo["number"]
    ));
    $loginKey = $stmt->fetch()[0];

    //2차 인증 여부
    $isTwoFactorAuth = false;
    if ($userInfo["two_factor_auth_key"] != null) {
        $isTwoFactorAuth = true;
    }

    //비밀번호 설정 여부
    $stmt = $pdo->prepare("SELECT password FROM user WHERE number = :number");
    $stmt->execute(array(
        ':number' => $userInfo["number"]
    ));
    $password = $stmt->fetch();
    $isNoPassword = true;
    if (isset($password["password"])) {
        $isNoPassword = false;
    }

?>

<div class = "user_info" style = "display: none;">
    <?php
        echo json_encode(array(
            "email" => $userInfo["email"],
            "nickname" => $userInfo["nickname"],
            "profile" => $userInfo["profile"],
            "description" => $userInfo["description"],
            "gender" => $userInfo["gender"],
            "birthDate" => array(
                "year" => $userInfo["birth_year"],
                "month" => $userInfo["birth_month"],
                "day" => $userInfo["birth_day"]
            ),
            "loginKey" => $loginKey,
            "rigorousAccessProcedures" => $userInfo["rigorous_access_procedures"],
            "isTwoFactorAuth" => $isTwoFactorAuth,
            "isNoPassword" => $isNoPassword
        ));
    ?>
</div>

<div class = "menu_my_account_personal_info">
    <div class = "menu_my_account_personal_info_top">
        <div class = "menu_my_account_personal_info_top_title">
            ...
        </div>
        <div class = "menu_my_account_personal_info_top_description">
            ...
        </div>
    </div>
    <div class = "menu_my_account_personal_info_line"></div>
    <div class = "menu_my_account_personal_info_box_wrap">
        <div class = "menu_my_account_personal_info_box">
            <div class = "menu_my_account_personal_info_box_title">
                ...
            </div>
            <div class = "menu_my_account_personal_info_box_description">
                ...
            </div>
            <div class = "menu_my_account_personal_info_box_items">
                <div class = "menu_my_account_personal_info_box_item md-ripples" onclick = "loadMyAccount_details('nickname');">
                    <div class = "menu_my_account_personal_info_box_item_icon">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 28"><path d="M16 17.672c0 1.359-0.891 2.328-2 2.328h-8c-1.109 0-2-0.969-2-2.328 0-2.422 0.594-5.109 3.062-5.109 0.766 0.438 1.797 1.188 2.938 1.188s2.172-0.75 2.938-1.188c2.469 0 3.062 2.688 3.062 5.109zM13.547 9.547c0 1.969-1.594 3.547-3.547 3.547s-3.547-1.578-3.547-3.547c0-1.953 1.594-3.547 3.547-3.547s3.547 1.594 3.547 3.547zM28 16.5v1c0 0.281-0.219 0.5-0.5 0.5h-9c-0.281 0-0.5-0.219-0.5-0.5v-1c0-0.281 0.219-0.5 0.5-0.5h9c0.281 0 0.5 0.219 0.5 0.5zM28 12.563v0.875c0 0.313-0.25 0.562-0.562 0.562h-8.875c-0.313 0-0.562-0.25-0.562-0.562v-0.875c0-0.313 0.25-0.562 0.562-0.562h8.875c0.313 0 0.562 0.25 0.562 0.562zM28 8.5v1c0 0.281-0.219 0.5-0.5 0.5h-9c-0.281 0-0.5-0.219-0.5-0.5v-1c0-0.281 0.219-0.5 0.5-0.5h9c0.281 0 0.5 0.219 0.5 0.5zM30 23.5v-19c0-0.266-0.234-0.5-0.5-0.5h-27c-0.266 0-0.5 0.234-0.5 0.5v19c0 0.266 0.234 0.5 0.5 0.5h5.5v-1.5c0-0.281 0.219-0.5 0.5-0.5h1c0.281 0 0.5 0.219 0.5 0.5v1.5h12v-1.5c0-0.281 0.219-0.5 0.5-0.5h1c0.281 0 0.5 0.219 0.5 0.5v1.5h5.5c0.266 0 0.5-0.234 0.5-0.5zM32 4.5v19c0 1.375-1.125 2.5-2.5 2.5h-27c-1.375 0-2.5-1.125-2.5-2.5v-19c0-1.375 1.125-2.5 2.5-2.5h27c1.375 0 2.5 1.125 2.5 2.5z"></path></svg>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_center">
                        <div class = "menu_my_account_personal_info_box_item_center_title">
                            ...
                        </div>
                        <div class = "menu_my_account_personal_info_box_item_center_value">
                            ...
                        </div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
                <div class = "menu_my_account_personal_info_box_line"></div>
                <div class = "menu_my_account_personal_info_box_item md-ripples" onclick = "openPopupContents('change_profile');">
                    <div class = "menu_my_account_personal_info_box_item_icon">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M24 19v-11c0-0.828-0.337-1.58-0.879-2.121s-1.293-0.879-2.121-0.879h-3.465l-1.703-2.555c-0.182-0.27-0.486-0.445-0.832-0.445h-6c-0.326 0.002-0.64 0.158-0.832 0.445l-1.703 2.555h-3.465c-0.828 0-1.58 0.337-2.121 0.879s-0.879 1.293-0.879 2.121v11c0 0.828 0.337 1.58 0.879 2.121s1.293 0.879 2.121 0.879h18c0.828 0 1.58-0.337 2.121-0.879s0.879-1.293 0.879-2.121zM22 19c0 0.276-0.111 0.525-0.293 0.707s-0.431 0.293-0.707 0.293h-18c-0.276 0-0.525-0.111-0.707-0.293s-0.293-0.431-0.293-0.707v-11c0-0.276 0.111-0.525 0.293-0.707s0.431-0.293 0.707-0.293h4c0.346 0 0.65-0.175 0.832-0.445l1.703-2.555h4.93l1.703 2.555c0.192 0.287 0.506 0.443 0.832 0.445h4c0.276 0 0.525 0.111 0.707 0.293s0.293 0.431 0.293 0.707zM17 13c0-1.38-0.561-2.632-1.464-3.536s-2.156-1.464-3.536-1.464-2.632 0.561-3.536 1.464-1.464 2.156-1.464 3.536 0.561 2.632 1.464 3.536 2.156 1.464 3.536 1.464 2.632-0.561 3.536-1.464 1.464-2.156 1.464-3.536zM15 13c0 0.829-0.335 1.577-0.879 2.121s-1.292 0.879-2.121 0.879-1.577-0.335-2.121-0.879-0.879-1.292-0.879-2.121 0.335-1.577 0.879-2.121 1.292-0.879 2.121-0.879 1.577 0.335 2.121 0.879 0.879 1.292 0.879 2.121z"></path></svg>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_center" profile = "true">
                        <div class = "menu_my_account_personal_info_box_item_center_title">
                            ...
                        </div>
                        <div class = "menu_my_account_personal_info_box_item_center_value" style = "display: flex;">
                            ...
                        </div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_profile">
                        <div class = "my_profile"></div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
                <div class = "menu_my_account_personal_info_box_line"></div>
                <div class = "menu_my_account_personal_info_box_item md-ripples" onclick = "loadMyAccount_details('my_page_description');">
                    <div class = "menu_my_account_personal_info_box_item_icon">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28 28"><path d="M23.031 14.266l0.609 0.797c0.172 0.219 0.125 0.516-0.078 0.688-1.563 1.219-5.156 3.984-5.313 4.109-1.109 0.906-2.609 2.156-4.234 2.141h-0.031c-1.625 0-3.125-1.234-4.234-2.141-0.172-0.141-3.641-2.812-5.172-4-0.219-0.172-0.266-0.469-0.094-0.688l0.578-0.812c0.172-0.234 0.5-0.281 0.719-0.094 1.062 0.828 2.562 1.984 4.781 3.687 0.781 0.594 2.328 2.047 3.422 2.047h0.031c1.094 0 2.641-1.453 3.422-2.047 2.297-1.766 3.828-2.938 4.891-3.781 0.219-0.172 0.531-0.125 0.703 0.094zM26 25.5v-14.5c-1.563-1.453-1.328-1.328-8.563-6.922-0.781-0.609-2.328-2.078-3.422-2.078h-0.031c-1.094 0-2.641 1.469-3.422 2.078-7.234 5.594-7 5.469-8.563 6.922v14.5c0 0.266 0.234 0.5 0.5 0.5h23c0.266 0 0.5-0.234 0.5-0.5zM28 11v14.5c0 1.375-1.125 2.5-2.5 2.5h-23c-1.375 0-2.5-1.125-2.5-2.5v-14.5c0-0.562 0.234-1.094 0.641-1.469 3.203-2.969 6.891-5.547 9.109-7.375 1.094-0.906 2.609-2.156 4.234-2.156h0.031c1.625 0 3.141 1.25 4.234 2.156 2.063 1.703 5.984 4.469 9.109 7.375 0.406 0.375 0.641 0.906 0.641 1.469z"></path></svg>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_center">
                        <div class = "menu_my_account_personal_info_box_item_center_title">
                            ...
                        </div>
                        <div class = "menu_my_account_personal_info_box_item_center_value" style = "white-space: pre-wrap;">
                            ...
                        </div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
                <div class = "menu_my_account_personal_info_box_line"></div>
                <div class = "menu_my_account_personal_info_box_item md-ripples" onclick = "loadMyAccount_details('gender');">
                    <div class = "menu_my_account_personal_info_box_item_icon">
                        ...
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_center">
                        <div class = "menu_my_account_personal_info_box_item_center_title">
                            ...
                        </div>
                        <div class = "menu_my_account_personal_info_box_item_center_value">
                            ...
                        </div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
                <div class = "menu_my_account_personal_info_box_line"></div>
                <div class = "menu_my_account_personal_info_box_item md-ripples" onclick = "loadMyAccount_details('birth_date');">
                    <div class = "menu_my_account_personal_info_box_item_icon">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,50A25.007,25.007,0,0,1,15.269,1.965,25.007,25.007,0,0,1,34.731,48.036,24.843,24.843,0,0,1,25,50ZM25,3A22,22,0,1,0,47,25,22.025,22.025,0,0,0,25,3Z"></path><g transform="translate(0 1)"><rect width="3" height="21" rx="1.5" transform="translate(23 6)"></rect><rect width="3" height="21" rx="1.5" transform="translate(44 24) rotate(90)"></rect></g></g></svg>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_center">
                        <div class = "menu_my_account_personal_info_box_item_center_title">
                            ...
                        </div>
                        <div class = "menu_my_account_personal_info_box_item_center_value">
                            ...
                        </div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
            </div>
        </div>
        <div class = "menu_my_account_personal_info_box">
            <div class = "menu_my_account_personal_info_box_title">
                ...
            </div>
            <div class = "menu_my_account_personal_info_box_description">
                ...
            </div>
            <div class = "menu_my_account_personal_info_box_items">
                <div class = "menu_my_account_personal_info_box_item md-ripples" onclick = "loadMyAccount_details('language');">
                    <div class = "menu_my_account_personal_info_box_item_icon">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><g transform="translate(0 -10)"><rect width="3" height="39" rx="1.5" transform="translate(13.339 12.326) rotate(20)"></rect><rect width="3" height="39" rx="1.5" transform="translate(12.35 13.352) rotate(-20)"></rect><rect width="3" height="15.5" rx="1.5" transform="translate(22.179 33.413) rotate(90)"></rect></g><g transform="translate(4.821 6)"><rect width="3" height="23.5" rx="1.5" transform="translate(45.179 15.413) rotate(90)"></rect><rect width="3" height="6.299" rx="1.5" transform="translate(34.929 17.589) rotate(180)"></rect><path d="M6.258-1.278A1.576,1.576,0,0,1,7.282.152s-3.4,8.118-4.351,14.5A42.123,42.123,0,0,0,3,26.749a1.5,1.5,0,0,1-3,0A46.581,46.581,0,0,1,.157,14.4C1.163,7.87,4.524-.436,4.524-.436A1.37,1.37,0,0,1,6.258-1.278Z" transform="translate(30.054 41.378) rotate(-150)"></path><path d="M-4.084.024A1.4,1.4,0,0,1-2.138.58,46.577,46.577,0,0,1,2.6,12.127a40.794,40.794,0,0,1,.4,11.8,1.5,1.5,0,0,1-3,0,25.612,25.612,0,0,0,0-10.38A49.119,49.119,0,0,0-4.77,1.8,1.48,1.48,0,0,1-4.084.024Z" transform="translate(39.585 41.423) rotate(150)"></path></g></g></svg>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_center">
                        <div class = "menu_my_account_personal_info_box_item_center_title">
                            ...
                        </div>
                        <div class = "menu_my_account_personal_info_box_item_center_value">
                            ...
                        </div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
                <div class = "menu_my_account_personal_info_box_line"></div>
                <div class = "menu_my_account_personal_info_box_item md-ripples" onclick = "loadMyAccount_details('location');">
                    <div class = "menu_my_account_personal_info_box_item_icon">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,50A25.007,25.007,0,0,1,15.269,1.965,25.007,25.007,0,0,1,34.731,48.036,24.843,24.843,0,0,1,25,50ZM25,3A22,22,0,1,0,47,25,22.025,22.025,0,0,0,25,3Z"></path><rect width="48" height="2" transform="translate(26 1) rotate(90)"></rect><path d="M0,0S11.775-11.288,23.775-11.288,48,0,48,0V2S35.775-9.288,23.775-9.288,0,2,0,2Z" transform="translate(26 1) rotate(90)"></path><path d="M0,0S11.775-11.288,23.775-11.288,48,0,48,0V2S35.775-9.288,23.775-9.288,0,2,0,2Z" transform="translate(24 49) rotate(-90)"></path><path d="M0,0S11.923-4.994,23.923-4.994,48,0,48,0V2S35.923-2.994,23.923-2.994,0,2,0,2Z" transform="translate(49 31.856) rotate(-180)"></path><path d="M0,0S11.923-4.994,23.923-4.994,48,0,48,0V2S35.923-2.994,23.923-2.994,0,2,0,2Z" transform="translate(1 17.85)"></path></g></svg>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_center">
                        <div class = "menu_my_account_personal_info_box_item_center_title">
                            ...
                        </div>
                        <div class = "menu_my_account_personal_info_box_item_center_value">
                            ...
                        </div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
                <div class = "menu_my_account_personal_info_box_line"></div>
                <div class = "menu_my_account_personal_info_box_item md-ripples" onclick = "loadMyAccount_details('screen_mode');">
                    <div class = "menu_my_account_personal_info_box_item_icon">
                        <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 50 50"><path d="M25,50A24.993,24.993,0,0,1,7.322,7.322,24.924,24.924,0,0,1,25,0a25.194,25.194,0,0,1,5.008.5A16,16,0,1,0,49.5,19.992,25.168,25.168,0,0,1,50,25,24.98,24.98,0,0,1,25,50ZM19.531,3.7h0a19.913,19.913,0,0,0-6.709,2.911,21.465,21.465,0,0,0-8.064,9.8A21.407,21.407,0,0,0,6.025,36.1a21.774,21.774,0,0,0,8.938,8.5,19.533,19.533,0,0,0,5.115,1.85,25.743,25.743,0,0,0,5.037.509,20.084,20.084,0,0,0,10.541-2.7,22.921,22.921,0,0,0,6.812-5.875,23.871,23.871,0,0,0,3.844-7.922,18.576,18.576,0,0,1-12.348,4.52c-.491,0-.994-.017-1.5-.051a18.923,18.923,0,0,1-9.677-3.61l-.224-.147a19.065,19.065,0,0,1-4.8-5.317,17.377,17.377,0,0,1-2.343-5.925A18.688,18.688,0,0,1,19.531,3.7Z" transform="translate(0 0)"></path></svg>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_center">
                        <div class = "menu_my_account_personal_info_box_item_center_title">
                            ...
                        </div>
                        <div class = "menu_my_account_personal_info_box_item_center_value">
                            ...
                        </div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
                <div class = "menu_my_account_personal_info_box_line"></div>
                <div class = "menu_my_account_personal_info_box_item md-ripples" onclick = "loadMyAccount_details('click_effect_speed');">
                    <div class = "menu_my_account_personal_info_box_item_icon">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 26 28"><path d="M10 2c-1.109 0-2 0.891-2 2v14l-2.359-3.156c-0.391-0.516-1.016-0.844-1.672-0.844-1.094 0-1.969 0.922-1.969 2 0 0.438 0.141 0.859 0.406 1.203l6 8c0.375 0.5 0.969 0.797 1.594 0.797h11.219c0.453 0 0.859-0.313 0.969-0.75l1.437-5.75c0.25-1 0.375-2.016 0.375-3.031v-3.391c0-0.828-0.641-1.578-1.5-1.578-0.828 0-1.5 0.672-1.5 1.5h-0.5v-0.953c0-0.984-0.75-1.797-1.75-1.797-0.969 0-1.75 0.781-1.75 1.75v1h-0.5v-1.406c0-1.125-0.859-2.094-2-2.094-1.109 0-2 0.891-2 2v1.5h-0.5v-8.906c0-1.125-0.859-2.094-2-2.094zM10 0c2.234 0 4 1.875 4 4.094v3.437c0.172-0.016 0.328-0.031 0.5-0.031 1.016 0 1.969 0.391 2.703 1.078 0.484-0.219 1.016-0.328 1.547-0.328 1.125 0 2.172 0.5 2.875 1.359 0.297-0.078 0.578-0.109 0.875-0.109 1.969 0 3.5 1.641 3.5 3.578v3.391c0 1.172-0.141 2.359-0.438 3.516l-1.437 5.75c-0.328 1.328-1.531 2.266-2.906 2.266h-11.219c-1.25 0-2.453-0.609-3.203-1.594l-6-8c-0.516-0.688-0.797-1.547-0.797-2.406 0-2.188 1.781-4 3.969-4 0.719 0 1.422 0.187 2.031 0.547v-8.547c0-2.203 1.797-4 4-4zM12 22v-6h-0.5v6h0.5zM16 22v-6h-0.5v6h0.5zM20 22v-6h-0.5v6h0.5z"></path></svg>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_center">
                        <div class = "menu_my_account_personal_info_box_item_center_title">
                            ...
                        </div>
                        <div class = "menu_my_account_personal_info_box_item_center_value">
                            ...
                        </div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
                <div class = "menu_my_account_personal_info_box_line"></div>
                <div class = "menu_my_account_personal_info_box_item md-ripples" onclick = "loadMyAccount_details('image_rendering');">
                    <div class = "menu_my_account_personal_info_box_item_icon">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M46,50H4a4,4,0,0,1-4-4V4A4,4,0,0,1,4,0H46a4,4,0,0,1,4,4V46A4.005,4.005,0,0,1,46,50ZM5,3A2,2,0,0,0,3,5V45a2,2,0,0,0,2,2H45a2,2,0,0,0,2-2V5a2,2,0,0,0-2-2Z"></path><rect width="3" height="25" rx="1.5" transform="translate(19.278 28.71) rotate(45)"></rect><rect width="3" height="14.85" rx="1.5" transform="translate(17.727 30.831) rotate(-45)"></rect><rect width="3" height="20.943" rx="1.5" transform="translate(37.002 21.694) rotate(30)"></rect><rect width="3" height="25" rx="1.5" transform="translate(35.451 23.194) rotate(-30)"></rect><path d="M8.5,17A8.5,8.5,0,1,1,17,8.5,8.51,8.51,0,0,1,8.5,17Zm0-14A5.5,5.5,0,1,0,14,8.5,5.506,5.506,0,0,0,8.5,3Z" transform="translate(10 8)"></path></g></svg>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_center">
                        <div class = "menu_my_account_personal_info_box_item_center_title">
                            ...
                        </div>
                        <div class = "menu_my_account_personal_info_box_item_center_value">
                            ...
                        </div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
            </div>
        </div>
        <div class = "menu_my_account_personal_info_box">
            <div class = "menu_my_account_personal_info_box_title">
                ...
            </div>
            <div class = "menu_my_account_personal_info_box_description">
                ...
            </div>
            <div class = "menu_my_account_personal_info_box_items">
                <div class = "menu_my_account_personal_info_box_item md-ripples" onclick = "loadMyAccount_details('password');">
                    <div class = "menu_my_account_personal_info_box_item_icon">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5 12h14c0.276 0 0.525 0.111 0.707 0.293s0.293 0.431 0.293 0.707v7c0 0.276-0.111 0.525-0.293 0.707s-0.431 0.293-0.707 0.293h-14c-0.276 0-0.525-0.111-0.707-0.293s-0.293-0.431-0.293-0.707v-7c0-0.276 0.111-0.525 0.293-0.707s0.431-0.293 0.707-0.293zM18 10v-3c0-1.657-0.673-3.158-1.757-4.243s-2.586-1.757-4.243-1.757-3.158 0.673-4.243 1.757-1.757 2.586-1.757 4.243v3h-1c-0.828 0-1.58 0.337-2.121 0.879s-0.879 1.293-0.879 2.121v7c0 0.828 0.337 1.58 0.879 2.121s1.293 0.879 2.121 0.879h14c0.828 0 1.58-0.337 2.121-0.879s0.879-1.293 0.879-2.121v-7c0-0.828-0.337-1.58-0.879-2.121s-1.293-0.879-2.121-0.879zM8 10v-3c0-1.105 0.447-2.103 1.172-2.828s1.723-1.172 2.828-1.172 2.103 0.447 2.828 1.172 1.172 1.723 1.172 2.828v3z"></path></svg>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_center">
                        <div class = "menu_my_account_personal_info_box_item_center_title">
                            ...
                        </div>
                        <div class = "menu_my_account_personal_info_box_item_center_value">
                            •••••••••••••••
                        </div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
                <div class = "menu_my_account_personal_info_box_line"></div>
                <div class = "menu_my_account_personal_info_box_item md-ripples" onclick = "loadMyAccount_details('email');">
                    <div class = "menu_my_account_personal_info_box_item_icon">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M3 7.921l8.427 5.899c0.34 0.235 0.795 0.246 1.147 0l8.426-5.899v10.079c0 0.272-0.11 0.521-0.295 0.705s-0.433 0.295-0.705 0.295h-16c-0.272 0-0.521-0.11-0.705-0.295s-0.295-0.433-0.295-0.705zM1 5.983c0 0.010 0 0.020 0 0.030v11.987c0 0.828 0.34 1.579 0.88 2.12s1.292 0.88 2.12 0.88h16c0.828 0 1.579-0.34 2.12-0.88s0.88-1.292 0.88-2.12v-11.988c0-0.010 0-0.020 0-0.030-0.005-0.821-0.343-1.565-0.88-2.102-0.541-0.54-1.292-0.88-2.12-0.88h-16c-0.828 0-1.579 0.34-2.12 0.88-0.537 0.537-0.875 1.281-0.88 2.103zM20.894 5.554l-8.894 6.225-8.894-6.225c0.048-0.096 0.112-0.183 0.188-0.259 0.185-0.185 0.434-0.295 0.706-0.295h16c0.272 0 0.521 0.11 0.705 0.295 0.076 0.076 0.14 0.164 0.188 0.259z"></path></svg>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_center">
                        <div class = "menu_my_account_personal_info_box_item_center_title">
                            ...
                        </div>
                        <div class = "menu_my_account_personal_info_box_item_center_value">
                            ...
                        </div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
            </div>
        </div>
        <div class = "menu_my_account_personal_info_box">
            <div class = "menu_my_account_personal_info_box_title">
                ...
            </div>
            <div class = "menu_my_account_personal_info_box_description">
                ...
            </div>
            <div class = "menu_my_account_personal_info_box_items">
                <div class = "menu_my_account_personal_info_box_item md-ripples" onclick = "loadMyAccount_session_list();">
                    <div class = "menu_my_account_personal_info_box_item_icon">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M20.293 1.293l-2 2c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0l2-2c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0zM12.092 10.898c-1.262-1.244-2.908-1.869-4.553-1.873-1.652-0.003-3.308 0.62-4.578 1.873-1.277 1.26-1.923 2.921-1.935 4.583s0.614 3.332 1.874 4.609c1.34 1.323 3.009 1.946 4.671 1.935s3.323-0.657 4.583-1.935 1.884-2.947 1.873-4.609-0.657-3.323-1.935-4.583zM10.688 12.322c0.885 0.873 1.332 2.020 1.339 3.173s-0.424 2.306-1.297 3.191-2.020 1.332-3.173 1.339-2.306-0.424-3.191-1.297c-0.916-0.927-1.347-2.080-1.339-3.233s0.455-2.3 1.339-3.173c0.879-0.867 2.023-1.299 3.169-1.296 1.141 0.002 2.279 0.435 3.152 1.296zM12.097 12.317l4.11-4.11c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0l-4.11 4.11c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0zM14.793 8.207l3 3c0.391 0.391 1.024 0.391 1.414 0l3.5-3.5c0.391-0.391 0.391-1.024 0-1.414l-3-3c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414l2.293 2.293-2.086 2.086-2.293-2.293c-0.391-0.391-1.024-0.391-1.414 0s-0.391 1.024 0 1.414zM16.207 8.207l3.5-3.5c0.391-0.391 0.391-1.024 0-1.414s-1.024-0.391-1.414 0l-3.5 3.5c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0z"></path></svg>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_center">
                        <div class = "menu_my_account_personal_info_box_item_center_title">
                            ...
                        </div>
                        <div class = "menu_my_account_personal_info_box_item_center_value">
                            ...
                        </div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
                <div class = "menu_my_account_personal_info_box_line"></div>
                <div class = "menu_my_account_personal_info_box_item md-ripples" onclick = "loadMyAccount_details('two_factor_auth');">
                    <div class = "menu_my_account_personal_info_box_item_icon">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M-1060.834,48.451a24.982,24.982,0,0,1-9.851-5.358,28.206,28.206,0,0,1-5.826-7.3A31.93,31.93,0,0,1-1080,26.576V7.411L-1060.834,0l19.524,8.024V26.576a21.064,21.064,0,0,1-3.676,9.973,29.222,29.222,0,0,1-6.642,6.791,38.884,38.884,0,0,1-9.206,5.111Zm.237-45.077h0l-16.489,6.133V26.32c2.587,8.765,6.933,13.468,10.123,15.869a16.8,16.8,0,0,0,6.366,3.143,43.062,43.062,0,0,0,8.04-5.156c3.682-3.014,8.1-7.864,8.231-13.857.253-11.486,0-16.155,0-16.2L-1060.6,3.373Z" transform="translate(1085.598 0.664)"></path></g></svg>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_center">
                        <div class = "menu_my_account_personal_info_box_item_center_title">
                            ...
                        </div>
                        <div class = "menu_my_account_personal_info_box_item_center_value">
                            ...
                        </div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
                <div class = "menu_my_account_personal_info_box_line"></div>
                <div class = "menu_my_account_personal_info_box_item md-ripples" onclick = "loadMyAccount_details('rigorous_access_procedures');">
                    <div class = "menu_my_account_personal_info_box_item_icon">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path d="M16.5 24.447v-0.996c3.352 0.099 5.993 1.174 5.993 2.487 0 1.379-2.906 2.56-6.492 2.56s-6.492-1.181-6.492-2.56c0-1.313 2.641-2.389 5.992-2.487v0.996c-2.799 0.069-4.993 0.71-4.993 1.491 0 0.827 2.459 1.623 5.493 1.623 3.033 0 5.492-0.796 5.492-1.623-0.001-0.781-2.194-1.421-4.993-1.491zM10.516 8.995c0-3.033 2.521-5.493 5.556-5.493 3.034 0 5.493 2.46 5.493 5.493 0 2.607-1.818 4.786-4.256 5.348l-1.309 13.219-1.313-13.256c-2.362-0.615-4.171-2.756-4.171-5.311zM16 7.524c0-0.828-0.671-1.498-1.498-1.498s-1.499 0.67-1.499 1.498c0 0.827 0.671 1.498 1.499 1.498s1.498-0.67 1.498-1.498z"></path></svg>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_center">
                        <div class = "menu_my_account_personal_info_box_item_center_title">
                            ...
                        </div>
                        <div class = "menu_my_account_personal_info_box_item_center_value">
                            ...
                        </div>
                    </div>
                    <div class = "menu_my_account_personal_info_box_item_right">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13.25 10l-7.141-7.42c-0.268-0.27-0.268-0.707 0-0.979 0.268-0.27 0.701-0.27 0.969 0l7.83 7.908c0.268 0.271 0.268 0.709 0 0.979l-7.83 7.908c-0.268 0.271-0.701 0.27-0.969 0s-0.268-0.707 0-0.979l7.141-7.417z"></path></svg>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>