<?php

    $menuNumber = $_POST["menuNumber"];

    include_once('../../default_function.php');
    $userInfo = getMyLoginInfo();

    if ($userInfo["isLogin"] == false) {
        echo 'not login'; exit;
    }

    $stmt = $pdo->prepare("SELECT number FROM works WHERE user_number = :user_number");
    $stmt->execute(array(
        ':user_number' => $userInfo["number"],
    ));
    $myWorks = array_reverse($stmt->fetchAll());
    $myWorksNumbers = array();
    for ($i = 0; $i < count($myWorks); $i++) {
        $myWorksNumbers[$i] = $myWorks[$i]["number"];
    }
    $myWorksInfoMaxCount = (count($myWorksNumbers) >= 15) ? 15 : count($myWorksNumbers);
    $myWorksInfo = getWorkInfo(implode(",", array_slice($myWorksNumbers, 0, $myWorksInfoMaxCount)));

?>

<div id = "my_works_numbers_<?php echo $menuNumber; ?>" style = "display: none;">
    <?php
        $myWorksNumbersStr = implode(",", $myWorksNumbers);
        echo $myWorksNumbersStr;
    ?>
</div>
<div id = "my_works_info_json_<?php echo $menuNumber; ?>" style = "display: none;">
    <?php echo json_encode($myWorksInfo); ?>
</div>

<div class = "my_works_contents">
    <div class = "my_works_contents_top">
        <div class = "sort_box md-ripples" popupwidth = "max-content" value = "0" onchange = "workspaceMyWorksOptionLoad(<?php echo $menuNumber; ?>);" onclick = "selectList(this, getMyWorksSortItems());">
            <div class = "sort_box_title value_title">
                <!-- 옵션 이름 -->
            </div>
            <div class = "sort_box_icon">
                <!-- Generated by IcoMoon.io -->
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M17.418 6.109c0.272-0.268 0.709-0.268 0.979 0s0.271 0.701 0 0.969l-7.908 7.83c-0.27 0.268-0.707 0.268-0.979 0l-7.908-7.83c-0.27-0.268-0.27-0.701 0-0.969s0.709-0.268 0.979 0l7.419 7.141 7.418-7.141z"></path></svg>
            </div>
        </div>
        <div class = "sort_box md-ripples" popupwidth = "max-content" value = "0" onchange = "workspaceMyWorksOptionLoad(<?php echo $menuNumber; ?>);" onclick = "selectList(this, getMyWorksWorkTypeItems());">
            <div class = "sort_box_title value_title">
                <!-- 옵션 이름 -->
            </div>
            <div class = "sort_box_icon">
                <!-- Generated by IcoMoon.io -->
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M17.418 6.109c0.272-0.268 0.709-0.268 0.979 0s0.271 0.701 0 0.969l-7.908 7.83c-0.27 0.268-0.707 0.268-0.979 0l-7.908-7.83c-0.27-0.268-0.27-0.701 0-0.969s0.709-0.268 0.979 0l7.419 7.141 7.418-7.141z"></path></svg>
            </div>
        </div>
    </div>
    <div class = "my_works_contents_items">
        <!-- 작품 리스트 -->
    </div>
    <div class = "my_works_contents_loading" style = "padding: 10px; display: none;">
        <div class="showbox"><div class="loader" style="width: 40px;"><svg class="circular" viewBox="25 25 50 50"><circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="5" stroke-miterlimit="10"></circle></svg></div></div>
    </div>
</div>