

<?php

    include_once('../../../default_function.php');
    $userInfo = getMyLoginInfo();

    $menuNumber = $_POST["menuNumber"];
    $data = $_POST["data"];
    $workNumber = (int) $data;

    //권한 체크
    $stmt = $pdo->prepare("SELECT number FROM works WHERE number = :number AND user_number = :user_number");
    $stmt->execute(array(
        'number' => $workNumber,
        'user_number' => $userInfo["number"]
    ));
    $works = $stmt->fetch();
    if (isset($works["number"]) == false) {
        echo "no_permission";
        exit;
    }

    $analysisInfo = getWorksAnalysisInfo($workNumber);

?>

<div class = "analysis_info" style = "display: none;">
    <?php echo json_encode($analysisInfo); ?>
</div>

<div class = "workspace_work_analysis">
    <div class = "workspace_work_analysis_top">
        <div class = "workspace_work_analysis_top_title">
            ...
        </div>
        <div class = "workspace_work_analysis_top_notice">
            <div class = "workspace_work_analysis_top_notice_icon">
                <!-- Generated by IcoMoon.io -->
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.070c-1.884-1.821-3.053-4.37-3.053-7.193 0-5.523 4.477-10 10-10 2.823 0 5.372 1.169 7.19 3.050l0.003 0.003c1.737 1.796 2.807 4.247 2.807 6.947 0 5.523-4.477 10-10 10-2.7 0-5.151-1.070-6.95-2.81l0.003 0.003zM9 5v6h2v-6h-2zM9 13v2h2v-2h-2z"></path></svg>
            </div>
            <div class = "workspace_work_analysis_top_notice_text">
                ...
            </div>
        </div>
    </div>
    <div class = "workspace_work_analysis_navigation scroll">
        <div class = "workspace_work_analysis_navigation_items">
            <div class = "workspace_work_analysis_navigation_item md-ripples" onclick = "workspaceWorkAnalysisNavigation(<?php echo $menuNumber; ?>, 0);">
                ...
            </div>
            <div class = "workspace_work_analysis_navigation_item md-ripples" onclick = "workspaceWorkAnalysisNavigation(<?php echo $menuNumber; ?>, 1);">
                ...
            </div>
        </div>
        <div class = "workspace_work_analysis_navigation_lines">
            <div class = "workspace_work_analysis_navigation_line"></div>
        </div>
    </div>

    <div class = "workspace_work_analysis_contents" order = "0">
        <div class = "workspace_work_analysis_contents_0">
            <div class = "workspace_work_analysis_summary">
                <div class = "workspace_work_analysis_summary_left">
                    <div class = "workspace_work_analysis_summary_title">
                        ...
                    </div>
                    <div class = "workspace_work_analysis_summary_category_items scroll">
                        <div class = "workspace_work_analysis_summary_category_item md-ripples" onclick = "workspaceWorkAnalysisSummaryGraphLoad(<?php echo $menuNumber; ?>, 0);">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><rect width="3" height="50" rx="1.5"></rect><rect width="3" height="50" rx="1.5" transform="translate(50 47) rotate(90)"></rect><rect width="3" height="18" rx="1.5" transform="translate(10 24)"></rect><rect width="3" height="28" rx="1.5" transform="translate(20 14)"></rect><rect width="3" height="11" rx="1.5" transform="translate(29 31)"></rect><rect width="3" height="21" rx="1.5" transform="translate(39 21)"></rect></g></svg>
                            <span>...</span>
                        </div>
                        <div class = "workspace_work_analysis_summary_category_item md-ripples" onclick = "workspaceWorkAnalysisSummaryGraphLoad(<?php echo $menuNumber; ?>, 1);">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><rect width="3" height="50" rx="1.5"></rect><rect width="3" height="50" rx="1.5" transform="translate(50 47) rotate(90)"></rect><rect width="3" height="18" rx="1.5" transform="translate(10 24)"></rect><rect width="3" height="28" rx="1.5" transform="translate(20 14)"></rect><rect width="3" height="11" rx="1.5" transform="translate(29 31)"></rect><rect width="3" height="21" rx="1.5" transform="translate(39 21)"></rect></g></svg>
                            <span>...</span>
                        </div>
                        <div class = "workspace_work_analysis_summary_category_item md-ripples" onclick = "workspaceWorkAnalysisSummaryGraphLoad(<?php echo $menuNumber; ?>, 2);">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><rect width="3" height="50" rx="1.5"></rect><rect width="3" height="50" rx="1.5" transform="translate(50 47) rotate(90)"></rect><rect width="3" height="18" rx="1.5" transform="translate(10 24)"></rect><rect width="3" height="28" rx="1.5" transform="translate(20 14)"></rect><rect width="3" height="11" rx="1.5" transform="translate(29 31)"></rect><rect width="3" height="21" rx="1.5" transform="translate(39 21)"></rect></g></svg>
                            <span>...</span>
                        </div>
                        <div class = "workspace_work_analysis_summary_category_item md-ripples" onclick = "workspaceWorkAnalysisSummaryGraphLoad(<?php echo $menuNumber; ?>, 3);">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><rect width="3" height="50" rx="1.5"></rect><rect width="3" height="50" rx="1.5" transform="translate(50 47) rotate(90)"></rect><rect width="3" height="18" rx="1.5" transform="translate(10 24)"></rect><rect width="3" height="28" rx="1.5" transform="translate(20 14)"></rect><rect width="3" height="11" rx="1.5" transform="translate(29 31)"></rect><rect width="3" height="21" rx="1.5" transform="translate(39 21)"></rect></g></svg>
                            <span>...</span>
                        </div>
                        <div class = "workspace_work_analysis_summary_category_item md-ripples" onclick = "workspaceWorkAnalysisSummaryGraphLoad(<?php echo $menuNumber; ?>, 4);">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><rect width="3" height="50" rx="1.5"></rect><rect width="3" height="50" rx="1.5" transform="translate(50 47) rotate(90)"></rect><rect width="3" height="18" rx="1.5" transform="translate(10 24)"></rect><rect width="3" height="28" rx="1.5" transform="translate(20 14)"></rect><rect width="3" height="11" rx="1.5" transform="translate(29 31)"></rect><rect width="3" height="21" rx="1.5" transform="translate(39 21)"></rect></g></svg>
                            <span>...</span>
                        </div>
                        <div class = "workspace_work_analysis_summary_category_item md-ripples" onclick = "workspaceWorkAnalysisSummaryGraphLoad(<?php echo $menuNumber; ?>, 5);">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><rect width="3" height="50" rx="1.5"></rect><rect width="3" height="50" rx="1.5" transform="translate(50 47) rotate(90)"></rect><rect width="3" height="18" rx="1.5" transform="translate(10 24)"></rect><rect width="3" height="28" rx="1.5" transform="translate(20 14)"></rect><rect width="3" height="11" rx="1.5" transform="translate(29 31)"></rect><rect width="3" height="21" rx="1.5" transform="translate(39 21)"></rect></g></svg>
                            <span>...</span>
                        </div>
                        <div class = "workspace_work_analysis_summary_category_item md-ripples" onclick = "workspaceWorkAnalysisSummaryGraphLoad(<?php echo $menuNumber; ?>, 6);">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><rect width="3" height="50" rx="1.5"></rect><rect width="3" height="50" rx="1.5" transform="translate(50 47) rotate(90)"></rect><rect width="3" height="18" rx="1.5" transform="translate(10 24)"></rect><rect width="3" height="28" rx="1.5" transform="translate(20 14)"></rect><rect width="3" height="11" rx="1.5" transform="translate(29 31)"></rect><rect width="3" height="21" rx="1.5" transform="translate(39 21)"></rect></g></svg>
                            <span>...</span>
                        </div>
                        <div class = "workspace_work_analysis_summary_category_item md-ripples" onclick = "workspaceWorkAnalysisSummaryGraphLoad(<?php echo $menuNumber; ?>, 7);">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><rect width="3" height="50" rx="1.5"></rect><rect width="3" height="50" rx="1.5" transform="translate(50 47) rotate(90)"></rect><rect width="3" height="18" rx="1.5" transform="translate(10 24)"></rect><rect width="3" height="28" rx="1.5" transform="translate(20 14)"></rect><rect width="3" height="11" rx="1.5" transform="translate(29 31)"></rect><rect width="3" height="21" rx="1.5" transform="translate(39 21)"></rect></g></svg>
                            <span>...</span>
                        </div>
                    </div>
                    <div class = "workspace_work_analysis_summary_graph">
                        <div class = "graph" data-type = "">
                            <div class = "graph-top">
                                <canvas class = "graph-canvas" width = "1" height = "1"></canvas>
                                <div class = "graph-info"></div>
                            </div>
                            <div class = "graph-bottom"></div>
                            <div class = "graph-value-view">
                                <div class = "graph-value-view-top">
                                    <span class = "graph-description">...</span>
                                    <span class = "graph-additional">...</span>
                                </div>
                                <span class = "graph-value">0</span>
                            </div>
                            <div class = "graph-value-differential-view">
                                <span class = "graph-differential-increase">...</span>
                                <span class = "graph-differential-description">...</span>
                            </div>
                        </div>
                    </div>
                    <div class = "workspace_work_analysis_summary_processing" style = "display: none;">
                        <!-- Generated by IcoMoon.io -->
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M4 5.002c0 0 0.003-0.095 0.213-0.288 0.245-0.225 0.671-0.483 1.306-0.73 1.499-0.585 3.821-0.984 6.481-0.984s4.982 0.399 6.482 0.984c0.634 0.247 1.061 0.505 1.306 0.73 0.205 0.189 0.212 0.281 0.212 0.288 0 0.003-0.007 0.095-0.213 0.284-0.245 0.225-0.671 0.483-1.306 0.73-1.499 0.585-3.821 0.984-6.481 0.984s-4.982-0.399-6.482-0.984c-0.634-0.247-1.061-0.505-1.306-0.73-0.208-0.192-0.212-0.284-0.212-0.284zM20 14.532v4.471c-0.041 0.097-0.096 0.181-0.217 0.291-0.245 0.225-0.671 0.482-1.303 0.728-1.495 0.582-3.809 0.978-6.48 0.978s-4.985-0.396-6.48-0.978c-0.633-0.246-1.058-0.503-1.303-0.728-0.12-0.11-0.176-0.194-0.199-0.242l-0.006-4.514c0.248 0.126 0.51 0.242 0.782 0.348 1.797 0.699 4.377 1.114 7.206 1.114s5.409-0.415 7.206-1.114c0.277-0.108 0.543-0.225 0.794-0.354zM20 7.527v4.463c0 0.004 0 0.008 0 0.013-0.041 0.097-0.096 0.181-0.217 0.291-0.245 0.225-0.671 0.482-1.303 0.728-1.495 0.582-3.809 0.978-6.48 0.978s-4.985-0.396-6.48-0.978c-0.633-0.246-1.058-0.503-1.303-0.728-0.12-0.11-0.176-0.194-0.199-0.242-0.001-0.040-0.004-0.079-0.009-0.117l-0.005-4.407c0.248 0.128 0.513 0.244 0.788 0.352 1.801 0.702 4.388 1.12 7.208 1.12s5.407-0.418 7.208-1.12c0.276-0.108 0.542-0.225 0.792-0.353zM2 5v14c0 0.058 0.002 0.116 0.007 0.174 0.057 0.665 0.425 1.197 0.857 1.594 0.498 0.457 1.175 0.824 1.93 1.118 1.797 0.699 4.377 1.114 7.206 1.114s5.409-0.415 7.206-1.114c0.755-0.294 1.432-0.661 1.93-1.118 0.432-0.397 0.8-0.929 0.857-1.594 0.005-0.058 0.007-0.116 0.007-0.174v-14c0-0.056-0.002-0.112-0.007-0.168-0.055-0.664-0.422-1.195-0.852-1.59-0.498-0.459-1.177-0.827-1.933-1.122-1.801-0.702-4.388-1.12-7.208-1.12s-5.407 0.418-7.208 1.12c-0.756 0.295-1.435 0.664-1.933 1.122-0.43 0.395-0.797 0.927-0.852 1.59-0.005 0.056-0.007 0.112-0.007 0.168z"></path></svg>
                        <div class = "workspace_work_analysis_summary_processing_title">
                            ...
                        </div>
                        <div class = "workspace_work_analysis_summary_processing_description">
                            ...
                        </div>
                    </div>
                    <div class = "workspace_work_analysis_summary_bottom_left">
                        <div class = "workspace_work_analysis_summary_bottom_top">
                            <div class = "workspace_work_analysis_summary_bottom_icon">
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M27,30H3a3,3,0,0,1-3-3V3A3,3,0,0,1,3,0H27a3,3,0,0,1,3,3V27A3,3,0,0,1,27,30ZM2.647,2.647V27.353H27.353V2.647Z" transform="translate(0 20)"></path><rect width="32" height="3" rx="1.5" transform="translate(8 10)"></rect><rect width="31" height="3" rx="1.5" transform="translate(40 10) rotate(90)"></rect><rect width="32" height="3" rx="1.5" transform="translate(18)"></rect><rect width="32" height="3" rx="1.5" transform="translate(50) rotate(90)"></rect></g></svg>
                            </div>
                            <div class = "workspace_work_analysis_summary_bottom_title">
                                ...
                            </div>
                        </div>
                        <div class = "workspace_work_analysis_summary_bottom_left_items">
                            <!-- item -->
                        </div>
                    </div>
                </div>
                <div class = "workspace_work_analysis_summary_right">
                    <div class = "workspace_work_analysis_summary_right_demographics">
                        <div class = "workspace_work_analysis_summary_right_demographics_contents">
                            <div class = "workspace_work_analysis_summary_right_demographics_contents_items">
                                <!-- item -->
                            </div>
                            <div class = "workspace_work_analysis_summary_right_demographics_contents_items">
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_item">
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_left">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M11,22A11,11,0,0,1,3.222,3.222,11,11,0,1,1,18.778,18.778,10.928,10.928,0,0,1,11,22ZM11,3a8,8,0,1,0,8,8A8.009,8.009,0,0,0,11,3Z" transform="translate(14)"></path><path d="M29.719,56H19A19,19,0,0,1,0,37V19A19,19,0,0,1,19,0H29.719a19,19,0,0,1,19,19V37a19,19,0,0,1-19,19Zm-11-52.5a16.018,16.018,0,0,0-16,16v18a16.018,16.018,0,0,0,16,16h11a16.018,16.018,0,0,0,16-16v-18a16.018,16.018,0,0,0-16-16Z" transform="translate(1.281 25)"></path></g></svg>
                                    </div>
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right">
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_title">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_value">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_lines">
                                            <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_line"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_line"></div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_item">
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_left">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><rect width="3" height="50" rx="1.5"></rect><rect width="3" height="32" rx="1.5" transform="translate(32) rotate(90)"></rect><rect width="3" height="32" rx="1.5" transform="translate(32 47) rotate(90)"></rect><g transform="translate(10)"><rect width="3" height="33" rx="1.5" transform="translate(39 24) rotate(90)"></rect><rect width="3" height="18" rx="1.5" transform="translate(40 25.585) rotate(135)"></rect><rect width="3" height="18" rx="1.5" transform="translate(37.879 23.686) rotate(45)"></rect></g></g></svg>
                                    </div>
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right">
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_title">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_value">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_lines">
                                            <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_line"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class = "workspace_work_analysis_summary_right_demographics_contents_items">
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_item">
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_left">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><g transform="translate(-1)"><path d="M-2147,24a11.923,11.923,0,0,1-8.486-3.515A11.922,11.922,0,0,1-2159,12a11.921,11.921,0,0,1,3.515-8.485A11.923,11.923,0,0,1-2147,0a11.921,11.921,0,0,1,8.485,3.515A11.921,11.921,0,0,1-2135,12a11.923,11.923,0,0,1-3.515,8.486A11.921,11.921,0,0,1-2147,24Zm0-21a9.01,9.01,0,0,0-9,9,9.01,9.01,0,0,0,9,9,9.01,9.01,0,0,0,9-9A9.01,9.01,0,0,0-2147,3Z" transform="translate(2161 4)"></path><rect width="3" height="20" rx="1.5" transform="translate(13 26)"></rect><rect width="3" height="19" rx="1.5" transform="translate(24 34) rotate(90)"></rect></g><rect width="3" height="20" rx="1.5" transform="translate(38.336 24) rotate(-180)"></rect><path d="M2195.887,6.993l-6.175,6.447s-1.324.736-2.06-.221a1.645,1.645,0,0,1,0-1.938l8.413-8.461a1.47,1.47,0,0,1,1.888,0c.907.809,8.412,8.461,8.412,8.461s.736,1.423-.147,2.109a1.815,1.815,0,0,1-1.962,0l-6.3-6.4Z" transform="translate(-2159.988 0.404)"></path><path d="M-2148,24a11.921,11.921,0,0,1-8.485-3.515A11.923,11.923,0,0,1-2160,12a11.921,11.921,0,0,1,3.515-8.485A11.921,11.921,0,0,1-2148,0a11.923,11.923,0,0,1,8.486,3.515A11.921,11.921,0,0,1-2136,12a11.923,11.923,0,0,1-3.515,8.486A11.922,11.922,0,0,1-2148,24Zm0-21a9.01,9.01,0,0,0-9,9,9.01,9.01,0,0,0,9,9,9.01,9.01,0,0,0,9-9A9.01,9.01,0,0,0-2148,3Z" transform="translate(2185 22)"></path></g></svg>
                                    </div>
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right">
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_title">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_value">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_lines">
                                            <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_line"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_line"></div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_item">
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_left">
                                        <svg style = "fill: var(--site-color-light);" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><g transform="translate(17.423 -21.984) rotate(45)"><rect width="3" height="23.183" rx="1.5" transform="translate(40.08 27.865) rotate(-180)"></rect><path d="M2197.25,7.714l-7.158,7.473s-1.535.853-2.388-.256a1.907,1.907,0,0,1,0-2.246l9.751-9.808a1.7,1.7,0,0,1,2.189,0c1.052.938,9.751,9.808,9.751,9.808s.853,1.649-.171,2.445a2.1,2.1,0,0,1-2.274,0l-7.306-7.416Z" transform="translate(-2159.617 0.404)"></path><path d="M14,28A14,14,0,0,1,4.1,4.1,14,14,0,1,1,23.9,23.9,13.909,13.909,0,0,1,14,28ZM14,3.5A10.5,10.5,0,1,0,24.5,14,10.512,10.512,0,0,0,14,3.5Z" transform="translate(24.58 24.865)"></path></g></g></svg>
                                    </div>
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right">
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_title">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_value">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_lines">
                                            <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_line"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_line"></div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_item">
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_left">
                                        <svg style = "fill: var(--color-failure);" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><g transform="translate(9.87 -3)"><path d="M13.5,27A13.5,13.5,0,0,1,3.954,3.954,13.5,13.5,0,1,1,23.046,23.046,13.41,13.41,0,0,1,13.5,27Zm0-23.625A10.125,10.125,0,1,0,23.625,13.5,10.136,10.136,0,0,0,13.5,3.375Z" transform="translate(2.13 4)"></path><rect width="3" height="23" rx="1.5" transform="translate(14.13 29)"></rect><rect width="3" height="23" rx="1.5" transform="translate(27.13 38) rotate(90)"></rect></g></g></svg>
                                    </div>
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right">
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_title">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_value">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_lines">
                                            <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_line"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class = "workspace_work_analysis_summary_right_demographics_contents_items">
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_item">
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_left">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,50A25.007,25.007,0,0,1,15.269,1.965,25.007,25.007,0,0,1,34.731,48.036,24.843,24.843,0,0,1,25,50ZM25,3A22,22,0,1,0,47,25,22.025,22.025,0,0,0,25,3Z"></path><g transform="translate(0 1)"><rect width="3" height="21" rx="1.5" transform="translate(23 6)"></rect><rect width="3" height="21" rx="1.5" transform="translate(44 24) rotate(90)"></rect></g></g></svg>
                                    </div>
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right">
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_title">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_value">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_lines">
                                            <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_line"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_line"></div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_item">
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_left">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,50A25.007,25.007,0,0,1,15.269,1.965,25.007,25.007,0,0,1,34.731,48.036,24.843,24.843,0,0,1,25,50ZM25,3A22,22,0,1,0,47,25,22.025,22.025,0,0,0,25,3Z"></path><g transform="translate(0 1)"><rect width="3" height="21" rx="1.5" transform="translate(23 6)"></rect><rect width="3" height="21" rx="1.5" transform="translate(44 24) rotate(90)"></rect></g></g></svg>
                                    </div>
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right">
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_title">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_value">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_lines">
                                            <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_line"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_line"></div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_item">
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_left">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,50A25.007,25.007,0,0,1,15.269,1.965,25.007,25.007,0,0,1,34.731,48.036,24.843,24.843,0,0,1,25,50ZM25,3A22,22,0,1,0,47,25,22.025,22.025,0,0,0,25,3Z"></path><g transform="translate(0 1)"><rect width="3" height="21" rx="1.5" transform="translate(23 6)"></rect><rect width="3" height="21" rx="1.5" transform="translate(44 24) rotate(90)"></rect></g></g></svg>
                                    </div>
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right">
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_title">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_value">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_lines">
                                            <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_line"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_line"></div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_item">
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_left">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,50A25.007,25.007,0,0,1,15.269,1.965,25.007,25.007,0,0,1,34.731,48.036,24.843,24.843,0,0,1,25,50ZM25,3A22,22,0,1,0,47,25,22.025,22.025,0,0,0,25,3Z"></path><g transform="translate(0 1)"><rect width="3" height="21" rx="1.5" transform="translate(23 6)"></rect><rect width="3" height="21" rx="1.5" transform="translate(44 24) rotate(90)"></rect></g></g></svg>
                                    </div>
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right">
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_title">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_value">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_lines">
                                            <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_line"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_line"></div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_item">
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_left">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,50A25.007,25.007,0,0,1,15.269,1.965,25.007,25.007,0,0,1,34.731,48.036,24.843,24.843,0,0,1,25,50ZM25,3A22,22,0,1,0,47,25,22.025,22.025,0,0,0,25,3Z"></path><g transform="translate(0 1)"><rect width="3" height="21" rx="1.5" transform="translate(23 6)"></rect><rect width="3" height="21" rx="1.5" transform="translate(44 24) rotate(90)"></rect></g></g></svg>
                                    </div>
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right">
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_title">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_value">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_lines">
                                            <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_line"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_line"></div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_item">
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_left">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,50A25.007,25.007,0,0,1,15.269,1.965,25.007,25.007,0,0,1,34.731,48.036,24.843,24.843,0,0,1,25,50ZM25,3A22,22,0,1,0,47,25,22.025,22.025,0,0,0,25,3Z"></path><g transform="translate(0 1)"><rect width="3" height="21" rx="1.5" transform="translate(23 6)"></rect><rect width="3" height="21" rx="1.5" transform="translate(44 24) rotate(90)"></rect></g></g></svg>
                                    </div>
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right">
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_title">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_value">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_lines">
                                            <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_line"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_line"></div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_item">
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_left">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,50A25.007,25.007,0,0,1,15.269,1.965,25.007,25.007,0,0,1,34.731,48.036,24.843,24.843,0,0,1,25,50ZM25,3A22,22,0,1,0,47,25,22.025,22.025,0,0,0,25,3Z"></path><g transform="translate(0 1)"><rect width="3" height="21" rx="1.5" transform="translate(23 6)"></rect><rect width="3" height="21" rx="1.5" transform="translate(44 24) rotate(90)"></rect></g></g></svg>
                                    </div>
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right">
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_title">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_value">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_lines">
                                            <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_line"></div>
                                        </div>
                                    </div>
                                </div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_line"></div>
                                <div class = "workspace_work_analysis_summary_right_demographics_contents_item">
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_left">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25,50A25.007,25.007,0,0,1,15.269,1.965,25.007,25.007,0,0,1,34.731,48.036,24.843,24.843,0,0,1,25,50ZM25,3A22,22,0,1,0,47,25,22.025,22.025,0,0,0,25,3Z"></path><g transform="translate(0 1)"><rect width="3" height="21" rx="1.5" transform="translate(23 6)"></rect><rect width="3" height="21" rx="1.5" transform="translate(44 24) rotate(90)"></rect></g></g></svg>
                                    </div>
                                    <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right">
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_title">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_value">
                                            ...
                                        </div>
                                        <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_lines">
                                            <div class = "workspace_work_analysis_summary_right_demographics_contents_item_right_line"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class = "workspace_work_analysis_summary_right_demographics_contents_items">
                                <!-- item -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class = "workspace_work_analysis_contents_1">
            <div class = "workspace_work_analysis_contents_analysis">
                <div class = "workspace_work_analysis_contents_analysis_items">
                    <!-- item -->
                </div>
            </div>
        </div>
        <div class = "workspace_work_analysis_contents_2">
            <!-- not contents -->
        </div>
    </div>
</div>