

<?php

    $menuNumber = $_POST["menuNumber"];
    $data = $_POST["data"];
    $workNumber = (int) $data;

    include_once('../../../default_function.php');
    $userInfo = getMyLoginInfo();

    if ($userInfo["isLogin"] == false) {
        echo 'not login'; exit;
    }

    $stmt = $pdo->prepare("SELECT number, original_language, chapter FROM works WHERE user_number = :user_number AND number = :number");
    $stmt->execute(array(
        ':user_number' => $userInfo["number"],
        ':number' => $workNumber,
    ));
    $work = $stmt->fetch();

    //권한 체크
    if (isset($work["number"]) == false) {
        echo "no permission";
    }

    //현지화 정보
    $stmt = $pdo->prepare("SELECT work_number, language, title, cover_image, title, description, tag FROM work_localization WHERE work_number = :work_number");
    $stmt->execute(array(
        ':work_number' => $workNumber,
    ));
    $localizationInfo = $stmt->fetchAll();
    $localizationInfo_count = count($localizationInfo);

    //챕터 현지화 정보
    $stmt = $pdo->prepare("SELECT language, chapter, title FROM work_chapter WHERE language is NOT NULL AND work_number = :work_number");
    $stmt->execute(array(
        ':work_number' => $workNumber,
    ));
    $chapterTitleInfo = $stmt->fetchAll();
    $chapterTitleInfo_count = count($chapterTitleInfo);

    $chapterTitle = array();
    for ($i = 0; $i < $chapterTitleInfo_count; $i++) {
        if (isset($chapterTitle[$chapterTitleInfo[$i]["language"]]) == false) {
            $chapterTitle[$chapterTitleInfo[$i]["language"]] = array();
        }
        $chapterTitle[$chapterTitleInfo[$i]["language"]][] = array(
            "chapter" => $chapterTitleInfo[$i]["chapter"],
            "title" => $chapterTitleInfo[$i]["title"]
        );
    }

    $info = array();
    for ($i = 0; $i < $localizationInfo_count; $i++) {
        $chapterTitleLocalization = null;
        if (isset($chapterTitle[$localizationInfo[$i]["language"]])) {
            $chapterTitleLocalization = $chapterTitle[$localizationInfo[$i]["language"]];
        }
        $info[] = array(
            'workNumber' => $localizationInfo[$i]["work_number"],
            'language' => $localizationInfo[$i]["language"],
            'coverImage' => $localizationInfo[$i]["cover_image"],
            'title' => $localizationInfo[$i]["title"],
            'description' => $localizationInfo[$i]["description"],
            'tag' => $localizationInfo[$i]["tag"],
            'chapterTitle' => $chapterTitleLocalization
        );
    }

?>

<div class = "work_number" style = "display: none;">
    <?php echo $workNumber; ?>
</div>
<div class = "work_chapter" style = "display: none;">
    <?php echo $work["chapter"]; ?>
</div>
<div class = "original_language" style = "display: none;">
    <?php echo $work["original_language"]; ?>
</div>
<div class = "info" style = "display: none;">
    <?php echo json_encode($info); ?>
</div>

<div class = "workspace_work_contents">
    <div class = "workspace_work_contents_left">
        <div class="workspace_work_contents_left_title">
            ...
        </div>
        <div class = "workspace_work_contents_localization">
            <div class = "workspace_work_contents_localization_top">
                <div class = "workspace_work_contents_localization_top_create_language md-ripples" onclick = "workspaceWorkLocalizationCreateLanguageButton(<?php echo $menuNumber; ?>);">
                    <!-- Generated by IcoMoon.io -->
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5 13h6v6c0 0.552 0.448 1 1 1s1-0.448 1-1v-6h6c0.552 0 1-0.448 1-1s-0.448-1-1-1h-6v-6c0-0.552-0.448-1-1-1s-1 0.448-1 1v6h-6c-0.552 0-1 0.448-1 1s0.448 1 1 1z"></path></svg>
                    <span>...</span>
                </div>
            </div>
            <div class = "workspace_work_contents_localization_items"></div>
            <div class = "menu_workspace_work_localization_no_data" style = "display: none;">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"/></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M-3094.635,49.5H-3116.5a3,3,0,0,1-3-3V3.5a3,3,0,0,1,3-3h31a3,3,0,0,1,3,3V37.365L-3094.635,49.5Z" transform="translate(3126)" opacity="0.7"/><path d="M3151.333,49.5l12.293-12.293h-9.846a2.517,2.517,0,0,0-1.983.575,2.884,2.884,0,0,0-.464,2.039Z" transform="translate(-3120)" opacity="0.6"/></g></svg>
                <div class = "menu_workspace_work_localization_no_data_title">
                    ...
                </div>
                <div class = "menu_workspace_work_localization_no_data_description">
                    ...
                </div>
            </div>
        </div>
    </div>
</div>