<?php

    include_once('../../default_function.php');

    $menuNumber = $_POST["menuNumber"];
    
    $trendingGenre = getTrendingGenre();
    $workNumbers = getTrendingWorkNumbers(); //인기 작품 구하기
    $numbers = explode(",", $workNumbers);
    $maxCount = (count($numbers) >= 24) ? 24 : count($numbers);
    $workInfo = getWorkInfo(implode(",", array_slice($numbers, 0, $maxCount)), null, null, false, true);

?>

<div class = "info" style = "display: none;">
    <?php
        echo json_encode(array(
            "genre" => $trendingGenre,
            "numbers" => $workNumbers,
            "info" => $workInfo
        ));
    ?>
</div>

<div class = "explore_trending">
    <div class = "explore_trending_banner">
        <div class = "explore_trending_banner_left">
            <div class = "explore_trending_banner_left_wrap">
                <div class = "explore_trending_banner_left_top">
                    <!-- Generated by IcoMoon.io -->
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M17 7h3.586l-7.086 7.086-4.293-4.293c-0.391-0.391-1.024-0.391-1.414 0l-7.5 7.5c-0.391 0.391-0.391 1.024 0 1.414s1.024 0.391 1.414 0l6.793-6.793 4.293 4.293c0.391 0.391 1.024 0.391 1.414 0l7.793-7.793v3.586c0 0.552 0.448 1 1 1s1-0.448 1-1v-6c0-0.136-0.027-0.265-0.076-0.383s-0.121-0.228-0.216-0.323c-0.001-0.001-0.001-0.001-0.002-0.002-0.092-0.092-0.202-0.166-0.323-0.216-0.118-0.049-0.247-0.076-0.383-0.076h-6c-0.552 0-1 0.448-1 1s0.448 1 1 1z"></path></svg>
                    <span>...</span>
                </div>
                <div class = "explore_trending_banner_left_title">
                    ...
                </div>
                <div class = "explore_trending_banner_left_description">
                    ...
                </div>
                <div class = "explore_trending_banner_left_learn_more">
                    <div class = "explore_trending_banner_left_learn_more_title">
                        ...
                    </div>
                    <div class = "explore_trending_banner_left_learn_more_button md-ripples" onclick = "loadMenu_explore();">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="50" height="50" viewBox="0 0 50 50"><defs><clipPath id="b"><rect width="50" height="50"></rect></clipPath></defs><g id="a" clip-path="url(#b)"><path d="M25-10a24.843,24.843,0,0,1-9.731-1.965,24.918,24.918,0,0,1-7.947-5.358,24.918,24.918,0,0,1-5.358-7.947A24.843,24.843,0,0,1,0-35a24.843,24.843,0,0,1,1.965-9.731,24.917,24.917,0,0,1,5.358-7.947,24.918,24.918,0,0,1,7.947-5.358A24.843,24.843,0,0,1,25-60a24.843,24.843,0,0,1,9.731,1.965,24.918,24.918,0,0,1,7.947,5.358,24.918,24.918,0,0,1,5.358,7.947A24.843,24.843,0,0,1,50-35a24.843,24.843,0,0,1-1.965,9.731,24.918,24.918,0,0,1-5.358,7.947,24.918,24.918,0,0,1-7.947,5.358A24.843,24.843,0,0,1,25-10Zm0-47A22.025,22.025,0,0,0,3-35,22.025,22.025,0,0,0,25-13,22.025,22.025,0,0,0,47-35,22.025,22.025,0,0,0,25-57Z" transform="translate(0 60)"></path><path d="M7-15.909v0L0-36.5,7-60l7,23.5L7-15.912Zm0-24.92a4,4,0,0,0-4,4,4.005,4.005,0,0,0,4,4,4,4,0,0,0,4-4A4,4,0,0,0,7-40.829Z" transform="translate(-6.788 46.763) rotate(45)"></path></g></svg>
                        <span>...</span>
                    </div>
                </div>
            </div>
            <div class = "explore_trending_banner_left_works scroll">
                <!-- item -->
            </div>
        </div>
        <div class = "explore_trending_banner_right" style = "height: 268px;">
            <div class = "explore_trending_banner_right_images_wrap">
                <div class = "explore_trending_banner_right_images">
                    <div class = "img_wrap">
                        <img src = "" onload = "imageLoad(event);" alt = "">
                    </div>
                    <div class = "img_wrap">
                        <img src = "" onload = "imageLoad(event);" alt = "">
                    </div>
                    <div class = "img_wrap">
                        <img src = "" onload = "imageLoad(event);" alt = "">
                    </div>
                    <div class = "img_wrap">
                        <img src = "" onload = "imageLoad(event);" alt = "">
                    </div>
                    <div class = "img_wrap">
                        <img src = "" onload = "imageLoad(event);" alt = "">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class = "explore_trending_category scroll">
        <div class = "explore_trending_category_item md-ripples explore_trending_category_item_selected" onclick = "exploreTrendingSelectGenre(<?php echo $menuNumber; ?>, null);">
            <span>...</span>
        </div>
    </div>
    <div class = "work_resizing work_contents">
        <!-- item -->
    </div>
    <div class = "menu_explore_trending_no_data">
        <!-- Generated by IcoMoon.io -->
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M7.734 9.984h-1.734q-1.641 0-2.813 1.195t-1.172 2.836 1.172 2.813 2.813 1.172h9.75zM3 5.25l1.266-1.266 16.734 16.734-1.266 1.266-2.016-1.969h-11.719q-2.484 0-4.242-1.758t-1.758-4.242q0-2.438 1.688-4.172t4.078-1.828zM19.359 10.031q1.922 0.141 3.281 1.57t1.359 3.398q0 2.578-2.109 4.078l-1.453-1.453q1.547-0.844 1.547-2.625 0-1.219-0.891-2.109t-2.109-0.891h-1.5v-0.516q0-2.297-1.594-3.891t-3.891-1.594q-1.313 0-2.531 0.609l-1.5-1.453q1.828-1.172 4.031-1.172 2.531 0 4.711 1.781t2.648 4.266z"></path></svg>
        <span>...</span>
    </div>
</div>
<div class = "home_explore_trending_contents_loading" style = "padding: 20px; display: none;">
    <div class="showbox"><div class="loader" style="width: 35px;"><svg class="circular" viewBox="25 25 50 50"><circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="5" stroke-miterlimit="10"></circle></svg></div></div>
</div>